export interface Language {
  code: string
  name: string
  nativeName: string
  speechCode: string // BCP-47 code for speech synthesis
  flag: string
}

export const SUPPORTED_LANGUAGES: Language[] = [
  // English
  { code: "en", name: "English", nativeName: "English", speechCode: "en-US", flag: "GB" },

  // Indian Languages
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", speechCode: "hi-IN", flag: "IN" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", speechCode: "bn-IN", flag: "IN" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", speechCode: "ta-IN", flag: "IN" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", speechCode: "te-IN", flag: "IN" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", speechCode: "mr-IN", flag: "IN" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", speechCode: "gu-IN", flag: "IN" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", speechCode: "kn-IN", flag: "IN" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", speechCode: "ml-IN", flag: "IN" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", speechCode: "pa-IN", flag: "IN" },


  // European Languages
  { code: "es", name: "Spanish", nativeName: "Español", speechCode: "es-ES", flag: "ES" },
  { code: "fr", name: "French", nativeName: "Français", speechCode: "fr-FR", flag: "FR" },
  { code: "de", name: "German", nativeName: "Deutsch", speechCode: "de-DE", flag: "DE" },
  { code: "it", name: "Italian", nativeName: "Italiano", speechCode: "it-IT", flag: "IT" },
  { code: "pt", name: "Portuguese", nativeName: "Português", speechCode: "pt-BR", flag: "BR" },
  { code: "ru", name: "Russian", nativeName: "Русский", speechCode: "ru-RU", flag: "RU" },

  // Asian Languages
  { code: "zh", name: "Chinese", nativeName: "中文", speechCode: "zh-CN", flag: "CN" },
  { code: "ja", name: "Japanese", nativeName: "日本語", speechCode: "ja-JP", flag: "JP" },
  { code: "ko", name: "Korean", nativeName: "한국어", speechCode: "ko-KR", flag: "KR" },
  { code: "th", name: "Thai", nativeName: "ไทย", speechCode: "th-TH", flag: "TH" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", speechCode: "vi-VN", flag: "VN" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", speechCode: "id-ID", flag: "ID" },

  // Middle Eastern
  { code: "ar", name: "Arabic", nativeName: "العربية", speechCode: "ar-SA", flag: "SA" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", speechCode: "tr-TR", flag: "TR" },
]

export const QUESTIONS: Record<string, string[]> = {
  en: [
    "How would you describe your overall mood over the past week?",
    "How well have you been sleeping recently?",
    "Have you been able to enjoy activities that usually bring you happiness?",
    "How connected do you feel to the people around you?",
    "How would you rate your energy levels lately?",
    "Have you been feeling anxious or worried about things?",
    "How are you managing stress in your daily life?",
    "Do you feel hopeful about the future?",
    "How would you describe your self-esteem right now?",
    "Is there anything specific that has been weighing on your mind?",
  ],
  hi: [
    "पिछले हफ्ते में आपका समग्र मूड कैसा रहा?",
    "हाल ही में आपकी नींद कैसी रही है?",
    "क्या आप उन गतिविधियों का आनंद ले पा रहे हैं जो आमतौर पर आपको खुशी देती हैं?",
    "आप अपने आसपास के लोगों से कितना जुड़ाव महसूस करते हैं?",
    "हाल ही में आपकी ऊर्जा का स्तर कैसा रहा है?",
    "क्या आप चिंतित या परेशान महसूस कर रहे हैं?",
    "आप अपने दैनिक जीवन में तनाव को कैसे संभाल रहे हैं?",
    "क्या आप भविष्य के बारे में आशावान महसूस करते हैं?",
    "इस समय आप अपने आत्म-सम्मान को कैसे बताएंगे?",
    "क्या कोई विशेष बात है जो आपके मन पर बोझ बनी हुई है?",
  ],
  bn: [
    "গত সপ্তাহে আপনার সামগ্রিক মেজাজ কেমন ছিল?",
    "সম্প্রতি আপনার ঘুম কেমন হচ্ছে?",
    "যে কাজগুলো সাধারণত আপনাকে খুশি করে সেগুলো কি উপভোগ করতে পারছেন?",
    "আপনার চারপাশের মানুষদের সাথে কতটা সংযুক্ত মনে করছেন?",
    "সম্প্রতি আপনার শক্তির মাত্রা কেমন?",
    "আপনি কি উদ্বিগ্ন বা চিন্তিত বোধ করছেন?",
    "আপনি কীভাবে দৈনন্দিন জীবনে মানসিক চাপ সামলাচ্ছেন?",
    "আপনি কি ভবিষ্যতের ব্যাপারে আশাবাদী?",
    "এই মুহূর্তে আপনার আত্মসম্মান কেমন?",
    "এমন কিছু আছে কি যা আপনার মনে বিশেষভাবে চেপে আছে?",
  ],
  ta: [
    "கடந்த வாரத்தில் உங்கள் ஒட்டுமொத்த மனநிலை எப்படி இருந்தது?",
    "சமீபத்தில் உங்கள் தூக்கம் எப்படி இருக்கிறது?",
    "வழக்கமாக உங்களுக்கு மகிழ்ச்சி தரும் செயல்களை அனுபவிக்க முடிகிறதா?",
    "உங்களைச் சுற்றியுள்ள மக்களுடன் எவ்வளவு இணைப்பாக உணர்கிறீர்கள்?",
    "சமீபத்தில் உங்கள் ஆற்றல் நிலை எப்படி இருக்கிறது?",
    "நீங்கள் பதற்றமாகவோ அல்லது கவலையாகவோ உணர்கிறீர்களா?",
    "அன்றாட வாழ்க்கையில் மன அழுத்தத்தை எப்படி சமாளிக்கிறீர்கள்?",
    "எதிர்காலத்தைப் பற்றி நம்பிக்கையாக உணர்கிறீர்களா?",
    "இப்போது உங்கள் சுயமரியாதை எப்படி இருக்கிறது?",
    "உங்கள் மனதில் குறிப்பாக ஏதாவது அழுத்தமாக இருக்கிறதா?",
  ],
  te: [
    "గత వారంలో మీ మొత్తం మానసిక స్థితి ఎలా ఉంది?",
    "ఇటీవల మీ నిద్ర ఎలా ఉంది?",
    "సాధారణంగా మీకు ఆనందం కలిగించే కార్యకలాపాలను ఆస్వాదించగలుగుతున్నారా?",
    "మీ చుట్టూ ఉన్న వ్యక్తులతో ఎంత అనుసంధానంగా ఉన్నారు?",
    "ఇటీవల మీ శక్తి స్థాయిలు ఎలా ఉన్నాయి?",
    "మీరు ఆందోళన లేదా ఆందోళన అనుభవిస్తున్నారా?",
    "రోజువారీ జీవితంలో ఒత్తిడిని ఎలా నిర్వహిస్తున్నారు?",
    "భవిష్యత్తు గురించి ఆశాజనకంగా భావిస్తున్నారా?",
    "ప్రస్తుతం మీ ఆత్మగౌరవం ఎలా ఉంది?",
    "మీ మనసులో ప్రత్యేకంగా ఏదైనా భారంగా ఉందా?",
  ],
  mr: [
    "गेल्या आठवड्यात तुमचा एकूण मूड कसा होता?",
    "अलीकडे तुमची झोप कशी आहे?",
    "जे उपक्रम सहसा तुम्हाला आनंद देतात ते तुम्ही आनंद घेऊ शकत आहात का?",
    "तुम्हाला तुमच्या आजूबाजूच्या लोकांशी किती जोडलेले वाटते?",
    "अलीकडे तुमची ऊर्जा पातळी कशी आहे?",
    "तुम्हाला चिंता किंवा काळजी वाटते का?",
    "तुम्ही दैनंदिन जीवनात ताण कसा हाताळत आहात?",
    "तुम्हाला भविष्याबद्दल आशावादी वाटते का?",
    "सध्या तुमचा आत्मसन्मान कसा आहे?",
    "काही विशेष गोष्ट तुमच्या मनावर दडपण आहे का?",
  ],
  gu: [
    "છેલ્લા અઠવાડિયામાં તમારો એકંદર મૂડ કેવો રહ્યો?",
    "તાજેતરમાં તમારી ઊંઘ કેવી છે?",
    "જે પ્રવૃત્તિઓ સામાન્ય રીતે તમને ખુશી આપે છે તેનો આનંદ માણી શકો છો?",
    "તમારી આસપાસના લોકો સાથે કેટલા જોડાયેલા અનુભવો છો?",
    "તાજેતરમાં તમારી ઊર્જાનું સ્તર કેવું છે?",
    "તમે ચિંતિત કે બેચેન અનુભવો છો?",
    "રોજિંદા જીવનમાં તણાવ કેવી રીતે સંભાળો છો?",
    "ભવિષ્ય વિશે આશાવાદી અનુભવો છો?",
    "હાલમાં તમારું આત્મસન્માન કેવું છે?",
    "કોઈ ખાસ વાત તમારા મન પર ભાર છે?",
  ],
  kn: [
    "ಕಳೆದ ವಾರದಲ್ಲಿ ನಿಮ್ಮ ಒಟ್ಟಾರೆ ಮನಸ್ಥಿತಿ ಹೇಗಿತ್ತು?",
    "ಇತ್ತೀಚೆಗೆ ನಿಮ್ಮ ನಿದ್ರೆ ಹೇಗಿದೆ?",
    "ಸಾಮಾನ್ಯವಾಗಿ ನಿಮಗೆ ಸಂತೋಷ ತರುವ ಚಟುವಟಿಕೆಗಳನ್ನು ಆನಂದಿಸಲು ಸಾಧ್ಯವಾಗುತ್ತಿದೆಯೇ?",
    "ನಿಮ್ಮ ಸುತ್ತಲಿನ ಜನರೊಂದಿಗೆ ಎಷ್ಟು ಸಂಪರ್ಕದಲ್ಲಿದ್ದೀರಿ?",
    "ಇತ್ತೀಚೆಗೆ ನಿಮ್ಮ ಶಕ್ತಿಯ ಮಟ್ಟ ಹೇಗಿದೆ?",
    "ನೀವು ಆತಂಕ ಅಥವಾ ಚಿಂತೆ ಅನುಭವಿಸುತ್ತಿದ್ದೀರಾ?",
    "ದೈನಂದಿನ ಜೀವನದಲ್ಲಿ ಒತ್ತಡವನ್ನು ಹೇಗೆ ನಿರ್ವಹಿಸುತ್ತಿದ್ದೀರಿ?",
    "ಭವಿಷ್ಯದ ಬಗ್ಗೆ ಆಶಾವಾದಿಯಾಗಿದ್ದೀರಾ?",
    "ಈಗ ನಿಮ್ಮ ಆತ್ಮಗೌರವ ಹೇಗಿದೆ?",
    "ನಿಮ್ಮ ಮನಸ್ಸಿನಲ್ಲಿ ಯಾವುದಾದರೂ ನಿರ್ದಿಷ್ಟ ಭಾರವಿದೆಯೇ?",
  ],
  ml: [
    "കഴിഞ്ഞ ആഴ്ചയിൽ നിങ്ങളുടെ മൊത്തത്തിലുള്ള മാനസികാവസ്ഥ എങ്ങനെയായിരുന്നു?",
    "സമീപകാലത്ത് നിങ്ങളുടെ ഉറക്കം എങ്ങനെയുണ്ട്?",
    "സാധാരണയായി നിങ്ങൾക്ക് സന്തോഷം നൽകുന്ന പ്രവർത്തനങ്ങൾ ആസ്വദിക്കാൻ കഴിയുന്നുണ്ടോ?",
    "നിങ്ങളുടെ ചുറ്റുമുള്ള ആളുകളുമായി എത്രത്തോളം ബന്ധപ്പെട്ടിരിക്കുന്നു?",
    "സമീപകാലത്ത് നിങ്ങളുടെ ഊർജ്ജ നിലവാരം എങ്ങനെയുണ്ട്?",
    "നിങ്ങൾ ഉത്കണ്ഠ അല്ലെങ്കിൽ ആശങ്ക അനുഭവിക്കുന്നുണ്ടോ?",
    "ദൈനംദിന ജീവിതത്തിൽ സമ്മർദ്ദം എങ്ങനെ കൈകാര്യം ചെയ്യുന്നു?",
    "ഭാവിയെക്കുറിച്ച് പ്രതീക്ഷയുണ്ടോ?",
    "ഇപ്പോൾ നിങ്ങളുടെ ആത്മാഭിമാനം എങ്ങനെയുണ്ട്?",
    "നിങ്ങളുടെ മനസ്സിൽ എന്തെങ്കിലും പ്രത്യേകമായി ഭാരമായിട്ടുണ്ടോ?",
  ],
  pa: [
    "ਪਿਛਲੇ ਹਫ਼ਤੇ ਤੁਹਾਡਾ ਸਮੁੱਚਾ ਮੂਡ ਕਿਵੇਂ ਰਿਹਾ?",
    "ਹਾਲ ਹੀ ਵਿੱਚ ਤੁਹਾਡੀ ਨੀਂਦ ਕਿਵੇਂ ਹੈ?",
    "ਕੀ ਤੁਸੀਂ ਉਹ ਗਤੀਵਿਧੀਆਂ ਆਨੰਦ ਮਾਣ ਸਕਦੇ ਹੋ ਜੋ ਆਮ ਤੌਰ 'ਤੇ ਤੁਹਾਨੂੰ ਖੁਸ਼ੀ ਦਿੰਦੀਆਂ ਹਨ?",
    "ਤੁਸੀਂ ਆਪਣੇ ਆਲੇ-ਦੁਆਲੇ ਦੇ ਲੋਕਾਂ ਨਾਲ ਕਿੰਨਾ ਜੁੜੇ ਮਹਿਸੂਸ ਕਰਦੇ ਹੋ?",
    "ਹਾਲ ਹੀ ਵਿੱਚ ਤੁਹਾਡੀ ਊਰਜਾ ਦਾ ਪੱਧਰ ਕਿਵੇਂ ਹੈ?",
    "ਕੀ ਤੁਸੀਂ ਚਿੰਤਤ ਜਾਂ ਫ਼ਿਕਰਮੰਦ ਮਹਿਸੂਸ ਕਰ ਰਹੇ ਹੋ?",
    "ਤੁਸੀਂ ਰੋਜ਼ਾਨਾ ਜ਼ਿੰਦਗੀ ਵਿੱਚ ਤਣਾਅ ਕਿਵੇਂ ਸੰਭਾਲ ਰਹੇ ਹੋ?",
    "ਕੀ ਤੁਸੀਂ ਭਵਿੱਖ ਬਾਰੇ ਆਸ਼ਾਵਾਦੀ ਮਹਿਸੂਸ ਕਰਦੇ ਹੋ?",
    "ਇਸ ਸਮੇਂ ਤੁਹਾਡਾ ਸਵੈ-ਮਾਣ ਕਿਵੇਂ ਹੈ?",
    "ਕੀ ਕੋਈ ਖ਼ਾਸ ਗੱਲ ਤੁਹਾਡੇ ਮਨ 'ਤੇ ਭਾਰੀ ਹੈ?",
  ],

  es: [
    "¿Cómo describirías tu estado de ánimo general durante la última semana?",
    "¿Cómo has dormido recientemente?",
    "¿Has podido disfrutar de actividades que normalmente te hacen feliz?",
    "¿Qué tan conectado te sientes con las personas a tu alrededor?",
    "¿Cómo calificarías tus niveles de energía últimamente?",
    "¿Has estado sintiéndote ansioso o preocupado por algo?",
    "¿Cómo estás manejando el estrés en tu vida diaria?",
    "¿Te sientes esperanzado sobre el futuro?",
    "¿Cómo describirías tu autoestima en este momento?",
    "¿Hay algo específico que te esté pesando en la mente?",
  ],
  fr: [
    "Comment décririez-vous votre humeur générale au cours de la semaine dernière?",
    "Comment avez-vous dormi récemment?",
    "Avez-vous pu profiter des activités qui vous rendent habituellement heureux?",
    "À quel point vous sentez-vous connecté aux personnes autour de vous?",
    "Comment évalueriez-vous votre niveau d'énergie dernièrement?",
    "Avez-vous ressenti de l'anxiété ou des inquiétudes?",
    "Comment gérez-vous le stress dans votre vie quotidienne?",
    "Vous sentez-vous optimiste pour l'avenir?",
    "Comment décririez-vous votre estime de soi en ce moment?",
    "Y a-t-il quelque chose de particulier qui vous pèse sur l'esprit?",
  ],
  de: [
    "Wie würden Sie Ihre allgemeine Stimmung in der letzten Woche beschreiben?",
    "Wie gut haben Sie in letzter Zeit geschlafen?",
    "Konnten Sie Aktivitäten genießen, die Ihnen normalerweise Freude bereiten?",
    "Wie verbunden fühlen Sie sich mit den Menschen um Sie herum?",
    "Wie würden Sie Ihr Energieniveau in letzter Zeit bewerten?",
    "Haben Sie sich ängstlich oder besorgt gefühlt?",
    "Wie gehen Sie mit Stress im Alltag um?",
    "Fühlen Sie sich hoffnungsvoll in Bezug auf die Zukunft?",
    "Wie würden Sie Ihr Selbstwertgefühl gerade beschreiben?",
    "Gibt es etwas Bestimmtes, das Ihnen auf der Seele liegt?",
  ],
  it: [
    "Come descriveresti il tuo umore generale nell'ultima settimana?",
    "Come hai dormito di recente?",
    "Sei riuscito a goderti le attività che di solito ti rendono felice?",
    "Quanto ti senti connesso con le persone intorno a te?",
    "Come valuteresti i tuoi livelli di energia ultimamente?",
    "Ti sei sentito ansioso o preoccupato per qualcosa?",
    "Come stai gestendo lo stress nella tua vita quotidiana?",
    "Ti senti speranzoso riguardo al futuro?",
    "Come descriveresti la tua autostima in questo momento?",
    "C'è qualcosa di specifico che ti pesa sulla mente?",
  ],
  pt: [
    "Como você descreveria seu humor geral na última semana?",
    "Como você tem dormido recentemente?",
    "Você tem conseguido aproveitar atividades que normalmente te trazem felicidade?",
    "Quão conectado você se sente com as pessoas ao seu redor?",
    "Como você avaliaria seus níveis de energia ultimamente?",
    "Você tem se sentido ansioso ou preocupado com algo?",
    "Como você está lidando com o estresse no seu dia a dia?",
    "Você se sente esperançoso sobre o futuro?",
    "Como você descreveria sua autoestima neste momento?",
    "Há algo específico que está pesando em sua mente?",
  ],
  ru: [
    "Как бы вы описали свое общее настроение за последнюю неделю?",
    "Как вы спали в последнее время?",
    "Удается ли вам наслаждаться занятиями, которые обычно приносят радость?",
    "Насколько связанным вы себя чувствуете с окружающими людьми?",
    "Как бы вы оценили свой уровень энергии в последнее время?",
    "Вы чувствовали тревогу или беспокойство?",
    "Как вы справляетесь со стрессом в повседневной жизни?",
    "Чувствуете ли вы надежду относительно будущего?",
    "Как бы вы описали свою самооценку сейчас?",
    "Есть ли что-то конкретное, что тяготит вас?",
  ],
  zh: [
    "您如何描述过去一周的整体情绪?",
    "您最近睡眠如何?",
    "您能够享受那些通常带给您快乐的活动吗?",
    "您感觉与周围的人联系紧密吗?",
    "您最近的精力水平如何?",
    "您是否感到焦虑或担忧?",
    "您如何管理日常生活中的压力?",
    "您对未来感到有希望吗?",
    "您现在如何描述您的自尊心?",
    "有什么特别的事情在困扰您吗?",
  ],
  ja: [
    "この1週間の全体的な気分はいかがでしたか?",
    "最近、よく眠れていますか?",
    "普段楽しいと感じる活動を楽しめていますか?",
    "周りの人とどのくらいつながりを感じていますか?",
    "最近のエネルギーレベルはいかがですか?",
    "不安や心配を感じていますか?",
    "日常生活でストレスをどのように管理していますか?",
    "将来に希望を感じていますか?",
    "現在の自尊心をどのように表現しますか?",
    "特に心に重くのしかかっていることはありますか?",
  ],
  ko: [
    "지난 한 주 동안의 전반적인 기분은 어땠나요?",
    "최근 잠은 잘 주무시고 계신가요?",
    "평소 행복을 주는 활동을 즐길 수 있으셨나요?",
    "주변 사람들과 얼마나 연결되어 있다고 느끼시나요?",
    "최근 에너지 수준은 어떠신가요?",
    "불안하거나 걱정되는 것들이 있으신가요?",
    "일상 생활에서 스트레스를 어떻게 관리하고 계신가요?",
    "미래에 대해 희망적으로 느끼시나요?",
    "현재 자존감은 어떠신가요?",
    "특별히 마음에 걸리는 것이 있으신가요?",
  ],
  th: [
    "คุณจะอธิบายอารมณ์โดยรวมของคุณในสัปดาห์ที่ผ่านมาอย่างไร?",
    "คุณนอนหลับเป็นอย่างไรบ้างเมื่อเร็วๆ นี้?",
    "คุณสามารถสนุกกับกิจกรรมที่ปกติทำให้คุณมีความสุขได้ไหม?",
    "คุณรู้สึกเชื่อมต่อกับคนรอบข้างมากแค่ไหน?",
    "คุณให้คะแนนระดับพลังงานของคุณช่วงนี้อย่างไร?",
    "คุณรู้สึกวิตกกังวลหรือเป็นห่วงเรื่องใดบ้างไหม?",
    "คุณจัดการกับความเครียดในชีวิตประจำวันอย่างไร?",
    "คุณรู้สึกมีความหวังเกี่ยวกับอนาคตไหม?",
    "คุณจะอธิบายความนับถือตนเองของคุณในตอนนี้อย่างไร?",
    "มีอะไรเฉพาะเจาะจงที่กดดันจิตใจคุณอยู่ไหม?",
  ],
  vi: [
    "Bạn sẽ mô tả tâm trạng chung của mình trong tuần qua như thế nào?",
    "Gần đây bạn ngủ có ngon không?",
    "Bạn có thể tận hưởng các hoạt động thường mang lại niềm vui cho bạn không?",
    "Bạn cảm thấy kết nối với những người xung quanh như thế nào?",
    "Bạn đánh giá mức năng lượng của mình gần đây như thế nào?",
    "Bạn có cảm thấy lo lắng hoặc bận tâm về điều gì không?",
    "Bạn quản lý stress trong cuộc sống hàng ngày như thế nào?",
    "Bạn có cảm thấy hy vọng về tương lai không?",
    "Bạn mô tả lòng tự trọng của mình hiện tại như thế nào?",
    "Có điều gì cụ thể đang đè nặng tâm trí bạn không?",
  ],
  id: [
    "Bagaimana Anda menggambarkan suasana hati Anda secara keseluruhan selama seminggu terakhir?",
    "Bagaimana tidur Anda akhir-akhir ini?",
    "Apakah Anda dapat menikmati aktivitas yang biasanya membuat Anda bahagia?",
    "Seberapa terhubung Anda dengan orang-orang di sekitar Anda?",
    "Bagaimana Anda menilai tingkat energi Anda akhir-akhir ini?",
    "Apakah Anda merasa cemas atau khawatir tentang sesuatu?",
    "Bagaimana Anda mengelola stres dalam kehidupan sehari-hari?",
    "Apakah Anda merasa penuh harapan tentang masa depan?",
    "Bagaimana Anda menggambarkan harga diri Anda saat ini?",
    "Adakah sesuatu yang spesifik yang membebani pikiran Anda?",
  ],
  ar: [
    "كيف تصف مزاجك العام خلال الأسبوع الماضي؟",
    "كيف كان نومك مؤخراً؟",
    "هل تمكنت من الاستمتاع بالأنشطة التي تجلب لك السعادة عادةً؟",
    "ما مدى شعورك بالتواصل مع الأشخاص من حولك؟",
    "كيف تقيّم مستويات طاقتك مؤخراً؟",
    "هل كنت تشعر بالقلق أو الانزعاج من أشياء؟",
    "كيف تدير التوتر في حياتك اليومية؟",
    "هل تشعر بالأمل تجاه المستقبل؟",
    "كيف تصف احترامك لذاتك الآن؟",
    "هل هناك شيء محدد يثقل على ذهنك؟",
  ],
  tr: [
    "Geçen hafta boyunca genel ruh halinizi nasıl tanımlarsınız?",
    "Son zamanlarda uykularınız nasıl?",
    "Genellikle sizi mutlu eden aktivitelerden keyif alabiliyor musunuz?",
    "Çevrenizdeki insanlarla ne kadar bağlantılı hissediyorsunuz?",
    "Son zamanlarda enerji seviyenizi nasıl değerlendirirsiniz?",
    "Endişeli veya kaygılı hissediyor musunuz?",
    "Günlük yaşamınızda stresi nasıl yönetiyorsunuz?",
    "Gelecek hakkında umutlu hissediyor musunuz?",
    "Şu anda özgüveninizi nasıl tanımlarsınız?",
    "Aklınızı meşgul eden belirli bir şey var mı?",
  ],
}

export const UI_TRANSLATIONS: Record<string, {
  brandName: string
  tagline: string
  howItWorks: string
  howItWorksDesc: string
  speakNaturally: string
  speakNaturallyDesc: string
  aiAnalysis: string
  aiAnalysisDesc: string
  personalReport: string
  personalReportDesc: string
  beginAssessment: string
  privateDisclaimer: string
  disclaimer: string
  selectLanguage: string
  recording: string
  tapToStop: string
  tapToStart: string
  processing: string
  typeResponse: string
  submit: string
  or: string
  reviewResponses: string
  reviewDesc: string
  doYouAgree: string
  yes: string
  no: string
  maybe: string
  generatingReport: string
  generatingReportDesc: string
  downloadReport: string
  startOver: string
  focusAreas: string
  strengths: string
  of: string
  assessmentGreeting: string
  assessmentClosing: string
  assessmentFallback: string
  changeAnalysis: string
  overridePositive: string
  overrideNeutral: string
  overrideNegative: string
  exitAssessment: string
  tapToBegin: string
  liveConversation: string
  liveConversationIntro: string
  statusIdle: string
  statusListening: string
  statusProcessing: string

  statusSpeaking: string
  askToSkip?: string
  skipConfirmed?: string
  priorityHigh: string
  priorityMedium: string
  priorityLow: string
  statusPositive: string
  statusBalanced: string
  statusNeedsSupport: string
}> = {
  en: {
    brandName: "MyGuru",
    tagline: "A voice-based mental health assessment tool",
    howItWorks: "How It Works",
    howItWorksDesc: "A simple, private way to check in with yourself",
    speakNaturally: "Speak Naturally",
    speakNaturallyDesc: "Answer 10 questions using your voice. Just speak naturally as you would to a friend.",
    aiAnalysis: "AI Analysis",
    aiAnalysisDesc: "Our AI analyzes the sentiment of your responses to understand your emotional state.",
    personalReport: "Personal Report",
    personalReportDesc: "Receive a personalized report with insights and recommendations for your wellbeing.",
    beginAssessment: "Begin Assessment",
    privateDisclaimer: "Your responses are processed privately and not stored",
    disclaimer: "This tool is for self-reflection purposes only and is not a substitute for professional mental health care. If you are in crisis, please contact a mental health professional or crisis hotline.",
    selectLanguage: "Select your preferred language",
    recording: "Recording...",
    tapToStop: "Tap to stop",
    tapToStart: "Tap to start speaking",
    processing: "Processing your response...",
    typeResponse: "Or type your response here...",
    submit: "Submit",
    or: "or",
    reviewResponses: "Review Your Responses",
    reviewDesc: "Here's a summary of your assessment. Please review the sentiment analysis.",
    doYouAgree: "Do you agree with this analysis?",
    yes: "Yes",
    no: "No",
    maybe: "Maybe",
    generatingReport: "Generating your report...",
    generatingReportDesc: "This may take a moment",
    downloadReport: "Download Report",
    startOver: "Start Over",
    focusAreas: "Focus Areas",
    strengths: "Your Strengths",
    of: "of",
    assessmentGreeting: "Hello. I am here to listen.",
    assessmentClosing: "Thank you for sharing. I'm generating your report now.",
    assessmentFallback: "I'm sorry, I didn't catch that. Could you please repeat?",
    changeAnalysis: "Change Analysis",
    overridePositive: "Positive",
    overrideNeutral: "Neutral",
    overrideNegative: "Needs Attention",
    exitAssessment: "Exit Assessment",
    tapToBegin: "Tap to Begin Conversation",
    liveConversation: "Live Conversation",
    liveConversationIntro: "Speak naturally using your microphone.",
    statusIdle: "Ready",
    statusListening: "Listening",
    statusProcessing: "Processing",
    statusSpeaking: "Speaking",
    askToSkip: "I couldn't hear you. Do you want to skip this question?",
    skipConfirmed: "Skipping question.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  hi: {
    brandName: "माईगुरु",
    tagline: "वॉयस-आधारित मानसिक स्वास्थ्य मूल्यांकन उपकरण",
    howItWorks: "यह कैसे काम करता है",
    howItWorksDesc: "अपने आप को जांचने का एक सरल, निजी तरीका",
    speakNaturally: "स्वाभाविक रूप से बोलें",
    speakNaturallyDesc: "अपनी आवाज़ से 10 सवालों का जवाब दें। जैसे आप किसी दोस्त से बात करते हैं वैसे ही बोलें।",
    aiAnalysis: "AI विश्लेषण",
    aiAnalysisDesc: "हमारा AI आपकी भावनात्मक स्थिति को समझने के लिए आपकी प्रतिक्रियाओं का विश्लेषण करता है।",
    personalReport: "व्यक्तिगत रिपोर्ट",
    personalReportDesc: "अपनी भलाई के लिए अंतर्दृष्टि और सिफारिशों के साथ एक व्यक्तिगत रिपोर्ट प्राप्त करें।",
    beginAssessment: "मूल्यांकन शुरू करें",
    privateDisclaimer: "आपकी प्रतिक्रियाएं निजी रूप से संसाधित की जाती हैं और संग्रहीत नहीं की जाती हैं",
    disclaimer: "यह उपकरण केवल आत्म-चिंतन के लिए है और पेशेवर मानसिक स्वास्थ्य देखभाल का विकल्प नहीं है।",
    selectLanguage: "अपनी पसंदीदा भाषा चुनें",
    recording: "रिकॉर्डिंग...",
    tapToStop: "रोकने के लिए टैप करें",
    tapToStart: "बोलना शुरू करने के लिए टैप करें",
    processing: "आपकी प्रतिक्रिया संसाधित हो रही है...",
    typeResponse: "या यहाँ अपना जवाब टाइप करें...",
    submit: "जमा करें",
    or: "या",
    reviewResponses: "अपनी प्रतिक्रियाओं की समीक्षा करें",
    reviewDesc: "यहां आपके मूल्यांकन का सारांश है। कृपया भावना विश्लेषण की समीक्षा करें।",
    doYouAgree: "क्या आप इस विश्लेषण से सहमत हैं?",
    yes: "हां",
    no: "नहीं",
    maybe: "शायद",
    generatingReport: "आपकी रिपोर्ट तैयार हो रही है...",
    generatingReportDesc: "इसमें कुछ समय लग सकता है",
    downloadReport: "रिपोर्ट डाउनलोड करें",
    startOver: "फिर से शुरू करें",
    focusAreas: "ध्यान देने वाले क्षेत्र",
    strengths: "आपकी ताकत",
    of: "का",
    assessmentGreeting: "नमस्ते। मैं सुनने के लिए यहाँ हूँ।",
    assessmentClosing: "साझा करने के लिए धन्यवाद। मैं अब आपकी रिपोर्ट तैयार कर रहा हूँ।",
    assessmentFallback: "क्षमा करें, मैं समझ नहीं पाया। क्या आप कृपया दोहरा सकते हैं?",
    changeAnalysis: "विश्लेषण बदलें",
    overridePositive: "सकारात्मक",
    overrideNeutral: "तटस्थ",
    overrideNegative: "ध्यान देने योग्य",
    exitAssessment: "मूल्यांकन से बाहर निकलें",
    tapToBegin: "बातचीत शुरू करने के लिए टैप करें",
    liveConversation: "लाइव बातचीत",
    liveConversationIntro: "अपने माइक्रोफ़ोन का उपयोग करके स्वाभाविक रूप से बोलें।",
    statusIdle: "तैयार",
    statusListening: "सुन रहा हूँ",
    statusProcessing: "प्रोसेसिंग",
    statusSpeaking: "बोल रहा हूँ",
    askToSkip: "मुझे सुनाई नहीं दिया। क्या आप इस प्रश्न को छोड़ना चाहते हैं?",
    skipConfirmed: "प्रश्न छोड़ा जा रहा है।",
    priorityHigh: "उच्च प्राथमिकता",
    priorityMedium: "मध्यम प्राथमिकता",
    priorityLow: "کم प्राथमिकता",
    statusPositive: "सकारात्मक",
    statusBalanced: "संतुलित",
    statusNeedsSupport: "सहायता की आवश्यकता",
  },
  bn: {
    brandName: "মাইগুরু",
    tagline: "ভয়েস-ভিত্তিক মানসিক স্বাস্থ্য মূল্যায়ন টুল",
    howItWorks: "এটি কীভাবে কাজ করে",
    howItWorksDesc: "নিজেকে পরীক্ষা করার একটি সহজ, ব্যক্তিগত উপায়",
    speakNaturally: "স্বাভাবিকভাবে কথা বলুন",
    speakNaturallyDesc: "আপনার কণ্ঠস্বর দিয়ে ১০টি প্রশ্নের উত্তর দিন। বন্ধুর সাথে যেমন কথা বলেন তেমনই।",
    aiAnalysis: "AI বিশ্লেষণ",
    aiAnalysisDesc: "আমাদের AI আপনার মানসিক অবস্থা বুঝতে আপনার উত্তর বিশ্লেষণ করে।",
    personalReport: "ব্যক্তিগত রিপোর্ট",
    personalReportDesc: "আপনার সুস্থতার জন্য অন্তর্দৃষ্টি এবং সুপারিশ সহ একটি ব্যক্তিগত রিপোর্ট পান।",
    beginAssessment: "মূল্যায়ন শুরু করুন",
    privateDisclaimer: "আপনার উত্তরগুলি ব্যক্তিগতভাবে প্রক্রিয়া করা হয় এবং সংরক্ষণ করা হয় না",
    disclaimer: "এই টুলটি শুধুমাত্র আত্ম-প্রতিফলনের জন্য এবং পেশাদার মানসিক স্বাস্থ্য সেবার বিকল্প নয়।",
    selectLanguage: "আপনার পছন্দের ভাষা নির্বাচন করুন",
    recording: "রেকর্ডিং...",
    tapToStop: "থামাতে ট্যাপ করুন",
    tapToStart: "বলা শুরু করতে ট্যাপ করুন",
    processing: "আপনার উত্তর প্রক্রিয়া করা হচ্ছে...",
    typeResponse: "বা এখানে আপনার উত্তর টাইপ করুন...",
    submit: "জমা দিন",
    or: "অথবা",
    reviewResponses: "আপনার উত্তরগুলি পর্যালোচনা করুন",
    reviewDesc: "এখানে আপনার মূল্যায়নের সারাংশ। অনুভূতি বিশ্লেষণ পর্যালোচনা করুন।",
    doYouAgree: "আপনি কি এই বিশ্লেষণের সাথে একমত?",
    yes: "হ্যাঁ",
    no: "না",
    maybe: "হয়তো",
    generatingReport: "আপনার রিপোর্ট তৈরি হচ্ছে...",
    generatingReportDesc: "এতে কিছু সময় লাগতে পারে",
    downloadReport: "রিপোর্ট ডাউনলোড করুন",
    startOver: "আবার শুরু করুন",
    focusAreas: "মনোযোগের ক্ষেত্র",
    strengths: "আপনার শক্তি",
    of: "এর",
    assessmentGreeting: "হ্যালো. আমি শুনতে এখানে আছি.",
    assessmentClosing: "শেয়ার করার জন্য ধন্যবাদ. আমি এখন আপনার রিপোর্ট তৈরি করছি.",
    assessmentFallback: "আমি দুঃখিত, আমি সেটা বুঝতে পারিনি। আপনি কি অনুগ্রহ করে পুনরাবৃত্তি করতে পারেন?",
    changeAnalysis: "বিশ্লেষণ পরিবর্তন করুন",
    overridePositive: "ইতিবাচক",
    overrideNeutral: "নিরপেক্ষ",
    overrideNegative: "মনোযোগ প্রয়োজন",
    exitAssessment: "মূল্যায়ন থেকে প্রস্থান করুন",
    tapToBegin: "কথোপকথন শুরু করতে আলতো চাপুন",
    liveConversation: "লাইভ কথোপকথন",
    liveConversationIntro: "আপনার মাইক্রোফোন ব্যবহার করে স্বাভাবিকভাবে কথা বলুন।",
    statusIdle: "প্রস্তুত",
    statusListening: "শুনছি",
    statusProcessing: "প্রক্রিয়া করা হচ্ছে",
    statusSpeaking: "বলছে",
    askToSkip: "আমি শুনতে পাইনি। আপনি কি এই প্রশ্নটি এড়িয়ে যেতে চান?",
    skipConfirmed: "প্রশ্ন এড়িয়ে যাওয়া হচ্ছে।",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  es: {
    brandName: "MyGuru",
    tagline: "Herramienta de evaluación de salud mental basada en voz",
    howItWorks: "Cómo Funciona",
    howItWorksDesc: "Una forma simple y privada de conectar contigo mismo",
    speakNaturally: "Habla Naturalmente",
    speakNaturallyDesc: "Responde 10 preguntas usando tu voz. Habla naturalmente como lo harías con un amigo.",
    aiAnalysis: "Análisis de IA",
    aiAnalysisDesc: "Nuestra IA analiza el sentimiento de tus respuestas para entender tu estado emocional.",
    personalReport: "Informe Personal",
    personalReportDesc: "Recibe un informe personalizado con ideas y recomendaciones para tu bienestar.",
    beginAssessment: "Comenzar Evaluación",
    privateDisclaimer: "Tus respuestas se procesan de forma privada y no se almacenan",
    disclaimer: "Esta herramienta es solo para autorreflexión y no sustituye la atención profesional de salud mental.",
    selectLanguage: "Selecciona tu idioma preferido",
    recording: "Grabando...",
    tapToStop: "Toca para detener",
    tapToStart: "Toca para empezar a hablar",
    processing: "Procesando tu respuesta...",
    typeResponse: "O escribe tu respuesta aquí...",
    submit: "Enviar",
    or: "o",
    reviewResponses: "Revisa Tus Respuestas",
    reviewDesc: "Aquí está el resumen de tu evaluación. Por favor revisa el análisis de sentimiento.",
    doYouAgree: "¿Estás de acuerdo con este análisis?",
    yes: "Sí",
    no: "No",
    maybe: "Tal vez",
    generatingReport: "Generando tu informe...",
    generatingReportDesc: "Esto puede tomar un momento",
    downloadReport: "Descargar Informe",
    startOver: "Comenzar de Nuevo",
    focusAreas: "Áreas de Enfoque",
    strengths: "Tus Fortalezas",
    of: "de",
    assessmentGreeting: "Hola. Estoy aquí para escuchar.",
    assessmentClosing: "Gracias por compartir. Generando tu reporte ahora.",
    assessmentFallback: "Lo siento, no entendí eso. ¿Podrías repetirlo, por favor?",
    changeAnalysis: "Cambiar Análisis",
    overridePositive: "Positivo",
    overrideNeutral: "Neutral",
    overrideNegative: "Necesita Atención",
    exitAssessment: "Salir de la Evaluación",
    tapToBegin: "Toque para Iniciar Conversación",
    liveConversation: "Conversación en Vivo",
    liveConversationIntro: "Hable naturalmente usando su micrófono.",
    statusIdle: "Listo",
    statusListening: "Escuchando",
    statusProcessing: "Procesando",
    statusSpeaking: "Hablando",
    askToSkip: "No te escuché. ¿Quieres saltar esta pregunta?",
    skipConfirmed: "Saltando pregunta.",
    priorityHigh: "Alta Prioridad",
    priorityMedium: "Prioridad Media",
    priorityLow: "Baja Prioridad",
    statusPositive: "Positivo",
    statusBalanced: "Equilibrado",
    statusNeedsSupport: "Necesita Apoyo",
  },
  fr: {
    brandName: "MyGuru",
    tagline: "Outil d'évaluation de santé mentale basé sur la voix",
    howItWorks: "Comment Ça Marche",
    howItWorksDesc: "Une façon simple et privée de faire le point sur vous-même",
    speakNaturally: "Parlez Naturellement",
    speakNaturallyDesc: "Répondez à 10 questions avec votre voix. Parlez naturellement comme avec un ami.",
    aiAnalysis: "Analyse IA",
    aiAnalysisDesc: "Notre IA analyse le sentiment de vos réponses pour comprendre votre état émotionnel.",
    personalReport: "Rapport Personnel",
    personalReportDesc: "Recevez un rapport personnalisé avec des insights et recommandations pour votre bien-être.",
    beginAssessment: "Commencer l'Évaluation",
    privateDisclaimer: "Vos réponses sont traitées de manière privée et non stockées",
    disclaimer: "Cet outil est uniquement pour l'auto-réflexion et ne remplace pas les soins professionnels de santé mentale.",
    selectLanguage: "Sélectionnez votre langue préférée",
    recording: "Enregistrement...",
    tapToStop: "Appuyez pour arrêter",
    tapToStart: "Appuyez pour commencer à parler",
    processing: "Traitement de votre réponse...",
    typeResponse: "Ou tapez votre réponse ici...",
    submit: "Soumettre",
    or: "ou",
    reviewResponses: "Révisez Vos Réponses",
    reviewDesc: "Voici un résumé de votre évaluation. Veuillez revoir l'analyse de sentiment.",
    doYouAgree: "Êtes-vous d'accord avec cette analyse?",
    yes: "Oui",
    no: "Non",
    maybe: "Peut-être",
    generatingReport: "Génération de votre rapport...",
    generatingReportDesc: "Cela peut prendre un moment",
    downloadReport: "Télécharger le Rapport",
    startOver: "Recommencer",
    focusAreas: "Domaines à Améliorer",
    strengths: "Vos Forces",
    of: "sur",
    assessmentGreeting: "Bonjour. Je suis là pour écouter.",
    assessmentClosing: "Merci d'avoir partagé. Je génère votre rapport maintenant.",
    assessmentFallback: "Je suis désolé, je n'ai pas compris. Pourriez-vous répéter ?",
    changeAnalysis: "Modifier l'analyse",
    overridePositive: "Positif",
    overrideNeutral: "Neutre",
    overrideNegative: "À surveiller",
    exitAssessment: "Quitter l'évaluation",
    tapToBegin: "Appuyez pour commencer",
    liveConversation: "Conversation en direct",
    liveConversationIntro: "Parlez naturellement en utilisant votre microphone.",
    statusIdle: "Prêt",
    statusListening: "Écoute",
    statusProcessing: "Traitement",
    statusSpeaking: "Parle",
    askToSkip: "Je ne vous ai pas entendu. Voulez-vous passer cette question ?",
    skipConfirmed: "Question passée.",
    priorityHigh: "Haute Priorité",
    priorityMedium: "Priorité Moyenne",
    priorityLow: "Basse Priorité",
    statusPositive: "Positif",
    statusBalanced: "Équilibré",
    statusNeedsSupport: "Besoin de Soutien",
  },
  zh: {
    brandName: "MyGuru",
    tagline: "基于语音的心理健康评估工具",
    howItWorks: "使用方法",
    howItWorksDesc: "一种简单、私密的自我检查方式",
    speakNaturally: "自然地说话",
    speakNaturallyDesc: "用您的声音回答10个问题。就像和朋友说话一样自然地说。",
    aiAnalysis: "AI分析",
    aiAnalysisDesc: "我们的AI分析您的回答情感,以了解您的情绪状态。",
    personalReport: "个人报告",
    personalReportDesc: "获取包含洞察和建议的个性化报告,促进您的身心健康。",
    beginAssessment: "开始评估",
    privateDisclaimer: "您的回答将被私密处理且不会被存储",
    disclaimer: "此工具仅用于自我反思,不能替代专业心理健康护理。",
    selectLanguage: "选择您的首选语言",
    recording: "录音中...",
    tapToStop: "点击停止",
    tapToStart: "点击开始说话",
    processing: "正在处理您的回答...",
    typeResponse: "或在此输入您的回答...",
    submit: "提交",
    or: "或",
    reviewResponses: "查看您的回答",
    reviewDesc: "这是您评估的摘要。请查看情感分析。",
    doYouAgree: "您同意这个分析吗?",
    yes: "是",
    no: "否",
    maybe: "也许",
    generatingReport: "正在生成您的报告...",
    generatingReportDesc: "这可能需要一点时间",
    downloadReport: "下载报告",
    startOver: "重新开始",
    focusAreas: "关注领域",
    strengths: "您的优势",
    of: "/",
    assessmentGreeting: "您好。我在这里倾听。",
    assessmentClosing: "感谢您的分享。我现在正在生成您的报告。",
    assessmentFallback: "对不起，我没听清。请您再说一遍好吗？",
    changeAnalysis: "更改分析",
    overridePositive: "积极",
    overrideNeutral: "中立",
    overrideNegative: "需关注",
    exitAssessment: "退出评估",
    tapToBegin: "点击开始对话",
    liveConversation: "实时对话",
    liveConversationIntro: "使用麦克风自然交谈。",
    statusIdle: "准备就绪",
    statusListening: "正在聆听",
    statusProcessing: "处理中",
    statusSpeaking: "正在说话",
    askToSkip: "我没听清。你想跳过这个问题吗？",
    skipConfirmed: "跳过问题。",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  ja: {
    brandName: "MyGuru",
    tagline: "音声ベースのメンタルヘルス評価ツール",
    howItWorks: "使い方",
    howItWorksDesc: "自分自身をチェックするシンプルでプライベートな方法",
    speakNaturally: "自然に話す",
    speakNaturallyDesc: "声で10の質問に答えてください。友人と話すように自然に話してください。",
    aiAnalysis: "AI分析",
    aiAnalysisDesc: "AIがあなたの回答の感情を分析し、感情状態を理解します。",
    personalReport: "パーソナルレポート",
    personalReportDesc: "あなたの健康のための洞察と推奨事項を含むパーソナライズされたレポートを受け取ります。",
    beginAssessment: "評価を開始",
    privateDisclaimer: "あなたの回答はプライベートに処理され、保存されません",
    disclaimer: "このツールは自己反省のためのものであり、専門的なメンタルヘルスケアの代わりにはなりません。",
    selectLanguage: "言語を選択してください",
    recording: "録音中...",
    tapToStop: "タップして停止",
    tapToStart: "タップして話し始める",
    processing: "回答を処理中...",
    typeResponse: "またはここに回答を入力...",
    submit: "送信",
    or: "または",
    reviewResponses: "回答を確認",
    reviewDesc: "これはあなたの評価の要約です。感情分析を確認してください。",
    doYouAgree: "この分析に同意しますか?",
    yes: "はい",
    no: "いいえ",
    maybe: "たぶん",
    generatingReport: "レポートを生成中...",
    generatingReportDesc: "少々お待ちください",
    downloadReport: "レポートをダウンロード",
    startOver: "最初からやり直す",
    focusAreas: "重点分野",
    strengths: "あなたの強み",
    of: "/",
    assessmentGreeting: "こんにちは。お話を聞くためにここにいます。",
    assessmentClosing: "共有していただきありがとうございます。現在レポートを作成しています。",
    assessmentFallback: "申し訳ありませんが、聞き取れませんでした。もう一度言っていただけますか？",
    changeAnalysis: "分析を変更",
    overridePositive: "ポジティブ",
    overrideNeutral: "ニュートラル",
    overrideNegative: "注意が必要",
    exitAssessment: "評価を終了",
    tapToBegin: "タップして会話を開始",
    liveConversation: "ライブ会話",
    liveConversationIntro: "マイクを使って自然に話してください。",
    statusIdle: "準備完了",
    statusListening: "聞き取り中",
    statusProcessing: "処理中",
    statusSpeaking: "話しています",
    askToSkip: "聞き取れませんでした。この質問をスキップしますか？",
    skipConfirmed: "質問をスキップします。",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  ko: {
    brandName: "MyGuru",
    tagline: "음성 기반 정신 건강 평가 도구",
    howItWorks: "사용 방법",
    howItWorksDesc: "자신을 점검하는 간단하고 개인적인 방법",
    speakNaturally: "자연스럽게 말하기",
    speakNaturallyDesc: "음성으로 10개의 질문에 답하세요. 친구와 대화하듯 자연스럽게 말씀하세요.",
    aiAnalysis: "AI 분석",
    aiAnalysisDesc: "AI가 응답의 감정을 분석하여 감정 상태를 파악합니다.",
    personalReport: "개인 보고서",
    personalReportDesc: "건강을 위한 통찰력과 권장 사항이 포함된 맞춤형 보고서를 받으세요.",
    beginAssessment: "평가 시작",
    privateDisclaimer: "응답은 비공개로 처리되며 저장되지 않습니다",
    disclaimer: "이 도구는 자기 성찰을 위한 것이며 전문적인 정신 건강 관리를 대체할 수 없습니다.",
    selectLanguage: "선호하는 언어를 선택하세요",
    recording: "녹음 중...",
    tapToStop: "탭하여 중지",
    tapToStart: "탭하여 말하기 시작",
    processing: "응답 처리 중...",
    typeResponse: "또는 여기에 응답을 입력하세요...",
    submit: "제출",
    or: "또는",
    reviewResponses: "응답 검토",
    reviewDesc: "평가 요약입니다. 감정 분석을 검토해 주세요.",
    doYouAgree: "이 분석에 동의하십니까?",
    yes: "예",
    no: "아니오",
    maybe: "아마도",
    generatingReport: "보고서 생성 중...",
    generatingReportDesc: "잠시만 기다려 주세요",
    downloadReport: "보고서 다운로드",
    startOver: "다시 시작",
    focusAreas: "집중 영역",
    strengths: "당신의 강점",
    of: "/",
    assessmentGreeting: "안녕하세요. 듣기 위해 여기 있습니다.",
    assessmentClosing: "공유해 주셔서 감사합니다. 지금 보고서를 생성하고 있습니다.",
    assessmentFallback: "죄송하지만, 잘 못 들었습니다. 다시 말씀해 주시겠습니까?",
    changeAnalysis: "분석 변경",
    overridePositive: "긍정적",
    overrideNeutral: "중립",
    overrideNegative: "Needs Attention",
    exitAssessment: "평가 종료",
    tapToBegin: "대화를 시작하려면 탭하세요",
    liveConversation: "실시간 대화",
    liveConversationIntro: "마이크를 사용하여 자연스럽게 말씀해 주세요.",

    statusIdle: "준비",
    statusListening: "듣는 중",
    statusProcessing: "처리 중",
    statusSpeaking: "말하는 중",
    askToSkip: "잘 못 들었습니다. 이 질문을 건너뛰시겠습니까?",
    skipConfirmed: "질문을 건너뜁니다.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  ta: {
    brandName: "மைகுரு",
    tagline: "குரல் வழி மனநல மதிப்பீட்டுக் கருவி",
    howItWorks: "எப்படி வேலை செய்கிறது",
    howItWorksDesc: "உங்களை நீங்களே பரிசோதிக்க ஒரு எளிய, தனிப்பட்ட வழி",
    speakNaturally: "இயல்பாக பேசுங்கள்",
    speakNaturallyDesc: "உங்கள் குரலைப் பயன்படுத்தி 10 கேள்விகளுக்கு பதிலளிக்கவும். நண்பரிடம் பேசுவது போல் இயல்பாக பேசுங்கள்.",
    aiAnalysis: "AI பகுப்பாய்வு",
    aiAnalysisDesc: "எங்கள் AI உங்கள் பதில்களின் உணர்வை பகுப்பாய்வு செய்து உங்கள் மன நிலையைப் புரிந்துகொள்கிறது.",
    personalReport: "தனிப்பட்ட அறிக்கை",
    personalReportDesc: "உங்கள் நலனுக்கான நுண்ணறிவு மற்றும் பரிந்துரைகளுடன் தனிப்பயனாக்கப்பட்ட அறிக்கையைப் பெறுங்கள்.",
    beginAssessment: "மதிப்பீட்டைத் தொடங்குங்கள்",
    privateDisclaimer: "உங்கள் பதில்கள் தனியாகச் செயலாக்கப்படுகின்றன மற்றும் சேமிக்கப்படாது",
    disclaimer: "இந்தக் கருவி சுய-பிரதிபலிப்பு நோக்கங்களுக்காக மட்டுமே மற்றும் தொழில்முறை மனநல சிகிச்சைக்கு மாற்றாகாது.",
    selectLanguage: "உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
    recording: "பதிவாகிறது...",
    tapToStop: "நிறுத்த தட்டவும்",
    tapToStart: "பேசத் தொடங்க தட்டவும்",
    processing: "உங்கள் பதில் செயலாக்கப்படுகிறது...",
    typeResponse: "அல்லது உங்கள் பதிலை இங்கே தட்டச்சு செய்யவும்...",
    submit: "சமர்ப்பிக்கவும்",
    or: "அல்லது",
    reviewResponses: "உங்கள் பதில்களை மதிப்பாய்வு செய்யவும்",
    reviewDesc: "உங்கள் மதிப்பீட்டின் சுருக்கம் இங்கே. தயவுசெய்து உணர்வுப் பகுப்பாய்வை மதிப்பாய்வு செய்யவும்.",
    doYouAgree: "இந்த பகுப்பாய்வை ஏற்கிறீர்களா?",
    yes: "ஆம்",
    no: "இல்லை",
    maybe: "இருக்கலாம்",
    generatingReport: "உங்கள் அறிக்கை தயாராகிறது...",
    generatingReportDesc: "இதற்கு சிறிது நேரம் ஆகலாம்",
    downloadReport: "அறிக்கையைப் பதிவிறக்கவும்",
    startOver: "மீண்டும் தொடங்கவும்",
    focusAreas: "கவனிக்க வேண்டிய பகுதிகள்",
    strengths: "உங்கள் பலங்கள்",
    of: "இல்",
    assessmentGreeting: "வணக்கம். நான் கேட்க இங்கே இருக்கிறேன்.",
    assessmentClosing: "பகிர்ந்தமைக்கு நன்றி. நான் இப்போது உங்கள் அறிக்கையை உருவாக்குகிறேன்.",
    assessmentFallback: "மன்னிக்கவும், எனக்குக் கேட்கவில்லை. தயவுசெய்து மீண்டும் சொல்ல முடியுமா?",
    changeAnalysis: "பகுப்பாய்வை மாற்றவும்",
    overridePositive: "நேர்மறை",
    overrideNeutral: "நடுநிலை",
    overrideNegative: "கவனம் தேவை",
    exitAssessment: "மதிப்பீட்டிலிருந்து வெளியேறு",
    tapToBegin: "உரையாடலைத் தொடங்க தட்டவும்",
    liveConversation: "நேரலை உரையாடல்",
    liveConversationIntro: "உங்கள் மைக்ரோஃபோனைப் பயன்படுத்தி இயல்பாகப் பேசுங்கள்.",
    statusIdle: "தயார்",
    statusListening: "கேட்கிறது",
    statusProcessing: "செயலாக்குகிறது",
    statusSpeaking: "பேசுகிறது",
    askToSkip: "என்னால் கேட்க முடியவில்லை. இந்தக் கேள்வியைத் தவிர்க்க விரும்புகிறீர்களா?",
    skipConfirmed: "கேள்வி தவிர்க்கப்படுகிறது.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  te: {
    brandName: "మైగురు",
    tagline: "వాయిస్-ఆధారిత మానసిక ఆరోగ్య అంచనా సాధనం",
    howItWorks: "ఇది ఎలా పనిచేస్తుంది",
    howItWorksDesc: "మిమ్మల్ని మీరు తనిఖీ చేసుకోవడానికి ఒక సాధారణ, ప్రైవేట్ మార్గం",
    speakNaturally: "సహజంగా మాట్లాడండి",
    speakNaturallyDesc: "మీ గొంతును ఉపయోగించి 10 ప్రశ్నలకు సమాధానం ఇవ్వండి. స్నేహితుడితో మాట్లాడినట్లు సహజంగా మాట్లాడండి.",
    aiAnalysis: "AI విశ్లేషణ",
    aiAnalysisDesc: "మా AI మీ భావోద్వేగ స్థితిని అర్థం చేసుకోవడానికి మీ ప్రతిస్పందనల సెంటిమెంట్‌ను విశ్లేషిస్తుంది.",
    personalReport: "వ్యక్తిగత నివేదిక",
    personalReportDesc: "మీ శ్రేయస్సు కోసం అంతర్దృష్టులు మరియు సిఫార్సులతో వ్యక్తిగతీకరించిన నివేదికను పొందండి.",
    beginAssessment: "అంచనాను ప్రారంభించండి",
    privateDisclaimer: "మీ స్పందనలు ప్రైవేట్‌గా ప్రాసెస్ చేయబడతాయి మరియు నిల్వ చేయబడవు",
    disclaimer: "ఈ సాధనం స్వీయ-పరామర్శ కోసం మాత్రమే మరియు వృత్తిపరమైన మానసిక ఆరోగ్య సంరక్షణకు ప్రత్యామ్నాయం కాదు.",
    selectLanguage: "మీకు నచ్చిన భాషను ఎంచుకోండి",
    recording: "రికార్డింగ్...",
    tapToStop: "ఆపడానికి నొక్కండి",
    tapToStart: "మాట్లాడటం ప్రారంభించడానికి నొక్కండి",
    processing: "మీ స్పందన ప్రాసెస్ చేయబడుతోంది...",
    typeResponse: "లేదా మీ సమాధానాన్ని ఇక్కడ టైప్ చేయండి...",
    submit: "సమర్పించండి",
    or: "లేదా",
    reviewResponses: "మీ స్పందనలను సమీక్షించండి",
    reviewDesc: "ఇక్కడ మీ అంచనా సారాంశం ఉంది. దయచేసి సెంటిమెంట్ విశ్లేషణను సమీక్షించండి.",
    doYouAgree: "మీరు ఈ విశ్లేషణతో ఏకీభవిస్తున్నారా?",
    yes: "అవును",
    no: "కాదు",
    maybe: "బహుశా",
    generatingReport: "మీ నివేదిక తయారవుతోంది...",
    generatingReportDesc: "దీనికి కొంత సమయం పట్టవచ్చు",
    downloadReport: "నివేదికను డౌన్‌లోడ్ చేయండి",
    startOver: "మళ్ళీ ప్రారంభించండి",
    focusAreas: "దృష్టి పెట్టవలసిన ప్రాంతాలు",
    strengths: "మీ బలాలు",
    of: "యొక్క",
    assessmentGreeting: "నమస్తే. నేను వినడానికి ఇక్కడ ఉన్నాను.",
    assessmentClosing: "భాగస్వామ్యం చేసినందుకు ధన్యవాదాలు. నేను ఇప్పుడు మీ నివేదికను రూపొందిస్తున్నాను.",
    assessmentFallback: "క్షమించండి, నాకు వినిపించలేదు. దయచేసి మళ్ళీ చెప్పగలరా?",
    changeAnalysis: "విశ్లేషణను మార్చండి",
    overridePositive: "సానుకూల",
    overrideNeutral: "తటస్థ",
    overrideNegative: "శ్రద్ధ అవసరం",
    exitAssessment: "అంచనా నుండి నిష్క్రమించు",
    tapToBegin: "సంభాషణ ప్రారంభించడానికి నొక్కండి",
    liveConversation: "లైవ్ సంభాషణ",
    liveConversationIntro: "మీ మైక్రోఫోన్ ఉపయోగించి సహజంగా మాట్లాడండి.",
    statusIdle: "సిద్ధంగా",
    statusListening: "వింటున్నాను",
    statusProcessing: "ప్రాసెస్ చేస్తోంది",
    statusSpeaking: "మాట్లాడుతున్నాను",
    askToSkip: "నాకు వినిపించలేదు. మీరు ఈ ప్రశ్నను దాటవేయాలనుకుంటున్నారా?",
    skipConfirmed: "ప్రశ్న దాటవేయబడుతోంది.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  mr: {
    brandName: "MyGuru",
    tagline: "आवाज-आधारित मानसिक आरोग्य मूल्यांकन साधन",
    howItWorks: "हे कसे कार्य करते",
    howItWorksDesc: "स्वतःला तपासण्याचा एक सोपा, खाजगी मार्ग",
    speakNaturally: "नैसर्गिकपणे बोला",
    speakNaturallyDesc: "तुमच्या आवाजाचा वापर करून 10 प्रश्नांची उत्तरे द्या. मित्राशी बोलल्यासारखे नैसर्गिकपणे बोला.",
    aiAnalysis: "AI विश्लेषण",
    aiAnalysisDesc: "आमचे AI तुमच्या भावनिक स्थितीला समजून घेण्यासाठी तुमच्या प्रतिक्रियांचे विश्लेषण करते.",
    personalReport: "वैयक्तिक अहवाल",
    personalReportDesc: "तुमच्या कल्याणासाठी अंतर्दृष्टी आणि शिफारसींसह वैयक्तिकृत अहवाल मिळवा.",
    beginAssessment: "मूल्यांकन सुरू करा",
    privateDisclaimer: "तुमच्या प्रतिक्रिया खाजगीरित्या प्रक्रिया केल्या जातात आणि साठवल्या जात नाहीत",
    disclaimer: "हे साधन केवळ आत्म-चिंतनासाठी आहे आणि व्यावसायिक मानसिक आरोग्य सेवेचा पर्याय नाही.",
    selectLanguage: "तुमची पसंतीची भाषा निवडा",
    recording: "रेकॉर्डिंग...",
    tapToStop: " थांबवण्यासाठी टॅप करा",
    tapToStart: "बोलणे सुरू करण्यासाठी टॅप करा",
    processing: "तुमची प्रतिक्रिया प्रक्रिया केली जात आहे...",
    typeResponse: "किंवा तुमचे उत्तर इथे टाईप करा...",
    submit: "सबमिट करा",
    or: "किंवा",
    reviewResponses: "तुमच्या प्रतिक्रियांचे पुनरावलोकन करा",
    reviewDesc: "येथे तुमच्या मूल्यांकनाचा सारांश आहे. कृपया भावना विश्लेषणाचे पुनरावलोकन करा.",
    doYouAgree: "तुम्ही या विश्लेषणाशी सहमत आहात का?",
    yes: "होय",
    no: "नाही",
    maybe: "कदाचित",
    generatingReport: "तुमचा अहवाल तयार होत आहे...",
    generatingReportDesc: "याला काही वेळ लागू शकतो",
    downloadReport: "अहवाल डाउनलोड करा",
    startOver: "पुन्हा सुरू करा",
    focusAreas: "लक्ष केंद्रित करण्याचे क्षेत्र",
    strengths: "तुमची ताकद",
    of: "पैकी",
    assessmentGreeting: "नमस्कार. मी ऐकण्यासाठी येथे आहे.",
    assessmentClosing: "सामायिक केल्याबद्दल धन्यवाद. मी आता तुमचा अहवाल तयार करत आहे.",
    assessmentFallback: "क्षमस्व, मला समजले नाही. कृपया पुन्हा सांगाल का?",
    changeAnalysis: "विश्लेषण बदला",
    overridePositive: "सकारात्मक",
    overrideNeutral: "तठस्थ",
    overrideNegative: "लक्ष देणे आवश्यक",
    exitAssessment: "मूल्यांकनातून बाहेर पडा",
    tapToBegin: "संभाषण सुरू करण्यासाठी टॅप करा",
    liveConversation: "थेट संभाषण",
    liveConversationIntro: "तुमचा मायक्रोफोन वापरून नैसर्गिकपणे बोला.",
    statusIdle: "तयार",
    statusListening: "ऐकत आहे",
    statusProcessing: "प्रक्रिया करत आहे",
    statusSpeaking: "बोलत आहे",
    askToSkip: "मला ऐकू आले नाही. तुम्हाला हा प्रश्न वगळायचा आहे का?",
    skipConfirmed: "प्रश्न वगळत आहे.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  gu: {
    brandName: "માયગુરુ",
    tagline: "અવાજ-આધારિત માનસિક સ્વાસ્થ્ય મૂલ્યાંકન સાધન",
    howItWorks: "તે કેવી રીતે કામ કરે છે",
    howItWorksDesc: "તમારી જાતને તપાસવાની એક સરળ, ખાનગી રીત",
    speakNaturally: "સ્વાભાવિક રીતે બોલો",
    speakNaturallyDesc: "તમારા અવાજનો ઉપયોગ કરીને 10 પ્રશ્નોના જવાબ આપો. મિત્ર સાથે વાત કરતા હો તેમ સ્વાભાવિક રીતે બોલો.",
    aiAnalysis: "AI વિશ્લેષણ",
    aiAnalysisDesc: "અમારું AI તમારી ભાવનાત્મક સ્થિતિને સમજવા માટે તમારા પ્રતિભાવોનું વિશ્લેષણ કરે છે.",
    personalReport: "વ્યક્તિગત અહેવાલ",
    personalReportDesc: "તમારી સુખાકારી માટે આંતરદૃષ્ટિ અને ભલામણો સાથે વ્યક્તિગત અહેવાલ મેળવો.",
    beginAssessment: "મૂલ્યાંકન શરૂ કરો",
    privateDisclaimer: "તમારા પ્રતિભાવો ખાનગી રીતે પ્રક્રિયા કરવામાં આવે છે અને સંગ્રહિત કરવામાં આવતા નથી",
    disclaimer: "આ સાધન માત્ર આત્મ-ચિંતન માટે છે અને વ્યાવસાયિક માનસિક સ્વાસ્થ્ય સંભાળનો વિકલ્પ નથી.",
    selectLanguage: "તમારી પસંદગીની ભાષા પસંદ કરો",
    recording: "રેકોર્ડિંગ...",
    tapToStop: "રોકવા માટે ટેપ કરો",
    tapToStart: "બોલવાનું શરૂ કરવા માટે ટેપ કરો",
    processing: "તમારો પ્રતિભાવ પ્રક્રિયા કરવામાં આવી રહ્યો છે...",
    typeResponse: "અથવા તમારો જવાબ અહીં લખો...",
    submit: "સબમિટ કરો",
    or: "અથવા",
    reviewResponses: "તમારા પ્રતિભાવોની સમીક્ષા કરો",
    reviewDesc: "અહીં તમારા મૂલ્યાંકનનો સારાંશ છે. કૃપા કરીને ભાવના વિશ્લેષણની સમીક્ષા કરો.",
    doYouAgree: "શું તમે આ વિશ્લેષણ સાથે સહમત છો?",
    yes: "હા",
    no: "ના",
    maybe: "કદાચ",
    generatingReport: "તમારો અહેવાલ તૈયાર થઈ રહ્યો છે...",
    generatingReportDesc: "આમાં થોડો સમય લાગી શકે છે",
    downloadReport: "અહેવાલ ડાઉનલોડ કરો",
    startOver: "ફરીથી શરૂ કરો",
    focusAreas: "ધ્યાન કેન્દ્રિત કરવાના ક્ષેત્રો",
    strengths: "તમારી શક્તિઓ",
    of: "નો",
    assessmentGreeting: "નમસ્તે. હું સાંભળવા માટે અહીં છું.",
    assessmentClosing: "શેર કરવા બદલ આભાર. હું હવે તમારો અહેવાલ તૈયાર કરી રહ્યો છું.",
    assessmentFallback: "માફ કરશો, હું સમજી શક્યો નહીં. શું તમે કૃપા કરીને ફરીથી કહી શકશો?",
    changeAnalysis: "વિશ્લેષણ બદલો",
    overridePositive: "સકારાત્મક",
    overrideNeutral: "તટસ્થ",
    overrideNegative: "ધ્યાન આપવાની જરૂર છે",
    exitAssessment: "મૂલ્યાંકનમાંથી બહાર નીકળો",
    tapToBegin: "વાતચીત શરૂ કરવા માટે ટેપ કરો",
    liveConversation: "લાઇવ વાતચીત",
    liveConversationIntro: "તમારા માઇક્રોફોનનો ઉપયોગ કરીને સ્વાભાવિક રીતે બોલો.",
    statusIdle: "તૈયાર",
    statusListening: "સાંભળી રહ્યો છું",
    statusProcessing: "પ્રક્રિયા થઈ રહી છે",
    statusSpeaking: "બોલી રહ્યો છું",
    askToSkip: "હું સાંભળી શક્યો નહીં. શું તમે આ પ્રશ્ન છોડવા માંગો છો?",
    skipConfirmed: "પ્રશ્ન છોડવામાં આવી રહ્યો છે.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  kn: {
    brandName: "ಮೈಗುರು",
    tagline: "ದನಿ ಆಧಾರಿತ ಮಾನಸಿಕ ಆರೋಗ್ಯ ಮೌಲ್ಯಮಾಪನ ಸಾಧನ",
    howItWorks: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    howItWorksDesc: "ನಿಮ್ಮನ್ನು ಪರಿಶೀಲಿಸಲು ಒಂದು ಸರಳ, ಖಾಸಗಿ ಮಾರ್ಗ",
    speakNaturally: "ಸಹಜವಾಗಿ ಮಾತನಾಡಿ",
    speakNaturallyDesc: "ನಿಮ್ಮ ಧ್ವನಿಯನ್ನು ಬಳಸಿಕೊಂಡು 10 ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ. ಸ್ನೇಹಿತರೊಂದಿಗೆ ಮಾತನಾಡುವಂತೆ ಸಹಜವಾಗಿ ಮಾತನಾಡಿ.",
    aiAnalysis: "AI ವಿಶ್ಲೇಷಣೆ",
    aiAnalysisDesc: "ನಮ್ಮ AI ನಿಮ್ಮ ಭಾವನಾತ್ಮಕ ಸ್ಥಿತಿಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗಳ ಭಾವನೆಯನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ.",
    personalReport: "ವೈಯಕ್ತಿಕ ವರದಿ",
    personalReportDesc: "ನಿಮ್ಮ ಯೋಗಕ್ಷೇಮಕ್ಕಾಗಿ ಒಳನೋಟಗಳು ಮತ್ತು ಶಿಫಾರಸುಗಳೊಂದಿಗೆ ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ವರದಿಯನ್ನು ಪಡೆಯಿರಿ.",
    beginAssessment: "ಮೌಲ್ಯಮಾಪನ ಪ್ರಾರಂಭಿಸಿ",
    privateDisclaimer: "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗಳನ್ನು ಖಾಸಗಿಯಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಸಂಗ್ರಹಿಸಲಾಗುವುದಿಲ್ಲ",
    disclaimer: "ಈ ಉಪಕರಣವು ಆತ್ಮಾವಲೋಕನಕ್ಕಾಗಿ ಮಾತ್ರ ಮತ್ತು ವೃತ್ತಿಪರ ಮಾನಸಿಕ ಆರೋಗ್ಯ ಆರೈಕೆಗೆ ಪರ್ಯಾಯವಲ್ಲ.",
    selectLanguage: "ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    recording: "ರೆಕಾರ್ಡಿಂಗ್...",
    tapToStop: "ನಿಲ್ಲಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    tapToStart: "ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    processing: "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
    typeResponse: "ಅಥವಾ ನಿಮ್ಮ ಉತ್ತರವನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...",
    submit: "ಸಲ್ಲಿಸಿ",
    or: "ಅಥವಾ",
    reviewResponses: "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
    reviewDesc: "ಇಲ್ಲಿ ನಿಮ್ಮ ಮೌಲ್ಯಮಾಪನದ ಸಾರಾಂಶವಿದೆ. ದಯವಿಟ್ಟು ಭಾವನೆ ವಿಶ್ಲೇಷಣೆಯನ್ನು ಪರಿಶೀಲಿಸಿ.",
    doYouAgree: "ನೀವು ಈ ವಿಶ್ಲೇಷಣೆಯನ್ನು ಒಪ್ಪುತ್ತೀರಾ?",
    yes: "ಹೌದು",
    no: "ಇಲ್ಲ",
    maybe: "ಬಹುಶಃ",
    generatingReport: "ನಿಮ್ಮ ವರದಿಯನ್ನು ರಚಿಸಲಾಗುತ್ತಿದೆ...",
    generatingReportDesc: "ಇದಕ್ಕೆ ಸ್ವಲ್ಪ ಸಮಯ ಬೇಕಾಗಬಹುದು",
    downloadReport: "ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    startOver: "ಮತ್ತೆ ಪ್ರಾರಂಭಿಸಿ",
    focusAreas: "ಗಮನ ಹರಿಸಬೇಕಾದ ಕ್ಷೇತ್ರಗಳು",
    strengths: "ನಿಮ್ಮ ಸಾಮರ್ಥ್ಯಗಳು",
    of: "ನ",
    assessmentGreeting: "ನಮಸ್ಕಾರ. ನಾನು ಕೇಳಲು ಇಲ್ಲಿದ್ದೇನೆ.",
    assessmentClosing: "ಹಂಚಿಕೊಂಡಿದ್ದಕ್ಕೆ ಧನ್ಯವಾದಗಳು. ನಾನು ಈಗ ನಿಮ್ಮ ವರದಿಯನ್ನು ರಚಿಸುತ್ತಿದ್ದೇನೆ.",
    assessmentFallback: "ಕ್ಷಮಿಸಿ, ನನಗೆ ಅರ್ಥವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಹೇಳಬಲ್ಲಿರಾ?",
    changeAnalysis: "ವಿಶ್ಲೇಷಣೆ ಬದಲಾಯಿಸಿ",
    overridePositive: "ಧನಾತ್ಮಕ",
    overrideNeutral: "ತಟಸ್ಥ",
    overrideNegative: "ಗಮನ ಬೇಕು",
    exitAssessment: "ಮೌಲ್ಯಮಾಪನದಿಂದ ನಿರ್ಗಮಿಸಿ",
    tapToBegin: "ಸಂಭಾಷಣೆ ಪ್ರಾರಂಭಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    liveConversation: "ಲೈವ್ ಸಂಭಾಷಣೆ",
    liveConversationIntro: "ನಿಮ್ಮ ಮೈಕ್ರೊಫೋನ್ ಬಳಸಿ ಸಹಜವಾಗಿ ಮಾತನಾಡಿ.",
    statusIdle: "ಸಿದ್ಧ",
    statusListening: "ಕೇಳುತ್ತಿದೆ",
    statusProcessing: "ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ",
    statusSpeaking: "ಮಾತನಾಡುತ್ತಿದೆ",
    askToSkip: "ನನಗೆ ಕೇಳಿಸಲಿಲ್ಲ. ನೀವು ಈ ಪ್ರಶ್ನೆಯನ್ನು ಬಿಟ್ಟುಬಿಡಲು ಬಯಸುತ್ತೀರಾ?",
    skipConfirmed: "ಪ್ರಶ್ನೆಯನ್ನು ಬಿಟ್ಟುಬಿಡಲಾಗುತ್ತಿದೆ.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  ml: {
    brandName: "മൈഗുരു",
    tagline: "ശബ്ദ-അധിഷ്ഠിത മാനസികാരോഗ്യ വിലയിരുത്തൽ ഉപകരണം",
    howItWorks: "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
    howItWorksDesc: "സ്വയം പരിശോധിക്കാനുള്ള ലളിതവും സ്വകാര്യവുമായ മാർഗ്ഗം",
    speakNaturally: "സ്വാഭാവികമായി സംസാരിക്കുക",
    speakNaturallyDesc: "നിങ്ങളുടെ ശബ്ദം ഉപയോഗിച്ച് 10 ചോദ്യങ്ങൾക്ക് ഉത്തരം നൽകുക. ഒരു സുഹൃത്തിനോട് സംസാരിക്കുന്നതുപോലെ സ്വാഭാവികമായി സംസാരിക്കുക.",
    aiAnalysis: "AI വിശകലനം",
    aiAnalysisDesc: "നിങ്ങളുടെ വൈകാരികാവസ്ഥ മനസ്സിലാക്കാൻ ഞങ്ങളുടെ AI നിങ്ങളുടെ പ്രതികരണങ്ങളുടെ വികാരം വിശകലനം ചെയ്യുന്നു.",
    personalReport: "വ്യക്തിഗത റിപ്പോർട്ട്",
    personalReportDesc: "നിങ്ങളുടെ ക്ഷേമത്തിനായുള്ള ഉൾക്കാഴ്ചകളും ശുപാർശകളും അടങ്ങിയ വ്യക്തിഗത റിപ്പോർട്ട് നേടുക.",
    beginAssessment: "വിലയിരുത്തൽ ആരംഭിക്കുക",
    privateDisclaimer: "നിങ്ങളുടെ പ്രതികരണങ്ങൾ സ്വകാര്യമായി പ്രോസസ്സ് ചെയ്യുന്നു, അവ സംഭരിക്കുന്നില്ല",
    disclaimer: "ഈ ഉപകരണം ആത്മപരിശോധനയ്ക്ക് മാത്രമുള്ളതാണ്, പ്രൊഫഷണൽ മാനസികാരോഗ്യ പരിരക്ഷയ്ക്ക് പകരമല്ല.",
    selectLanguage: "നിങ്ങളുടെ ഇഷ്ട ഭാഷ തിരഞ്ഞെടുക്കുക",
    recording: "റെക്കോർഡിംഗ്...",
    tapToStop: "നിർത്താൻ ടാപ്പ് ചെയ്യുക",
    tapToStart: "സംസാരിക്കാൻ ടാപ്പ് ചെയ്യുക",
    processing: "നിങ്ങളുടെ പ്രതികരണം പ്രോസസ്സ് ചെയ്യുന്നു...",
    typeResponse: "അല്ലെങ്കിൽ നിങ്ങളുടെ ഉത്തരം ഇവിടെ ടൈപ്പ് ചെയ്യുക...",
    submit: "സമർപ്പിക്കുക",
    or: "അല്ലെങ്കിൽ",
    reviewResponses: "നിങ്ങളുടെ പ്രതികരണങ്ങൾ അവലോകനം ചെയ്യുക",
    reviewDesc: "നിങ്ങളുടെ വിലയിരുത്തലിന്റെ സംഗ്രഹം ഇതാ. ദയവായി വികാര വിശകലനം അവലോകനം ചെയ്യുക.",
    doYouAgree: "ഈ വിശകലനത്തോട് നിങ്ങൾ യോജിക്കുന്നുണ്ടോ?",
    yes: "അതെ",
    no: "അല്ല",
    maybe: "ചിലപ്പോൾ",
    generatingReport: "നിങ്ങളുടെ റിപ്പോർട്ട് തയ്യാറാക്കുന്നു...",
    generatingReportDesc: "ഇതിന് കുറച്ച് സമയമെടുത്തേക്കാം",
    downloadReport: "റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക",
    startOver: "വീണ്ടും ആരംഭിക്കുക",
    focusAreas: "ശ്രദ്ധ കേന്ദ്രീകരിക്കേണ്ട മേഖലകൾ",
    strengths: "നിങ്ങളുടെ കരുത്ത്",
    of: "ന്റെ",
    assessmentGreeting: "നമസ്കാരം. ഞാൻ കേൾക്കാൻ ഇവിടെയുണ്ട്.",
    assessmentClosing: "പങ്കുവെച്ചതിന് നന്ദി. ഞാൻ ഇപ്പോൾ നിങ്ങളുടെ റിപ്പോർട്ട് തയ്യാറാക്കുകയാണ്.",
    assessmentFallback: "ക്ഷമിക്കണം, എനിക്ക് മനസ്സിലായില്ല. ദയവായി ഒന്നുകൂടി പറയാമോ?",
    changeAnalysis: "വിശകലനം മാറ്റുക",
    overridePositive: "പോസിറ്റീവ്",
    overrideNeutral: "ന്യൂട്രൽ",
    overrideNegative: "ശ്രദ്ധ ആവശ്യമാണ്",
    exitAssessment: "വിലയിരുത്തലിൽ നിന്ന് പുറത്തുകടക്കുക",
    tapToBegin: "സംഭാഷണം ആരംഭിക്കാൻ ടാപ്പ് ചെയ്യുക",
    liveConversation: "ലൈവ് സംഭാഷണം",
    liveConversationIntro: "നിങ്ങളുടെ മൈക്രോഫോൺ ഉപയോഗിച്ച് സ്വാഭാവികമായി സംസാരിക്കുക.",
    statusIdle: "തയ്യാർ",
    statusListening: "ശ്രദ്ധിക്കുന്നു",
    statusProcessing: "പ്രോസസ്സിംഗ്",
    statusSpeaking: "സംസാരിക്കുന്നു",
    askToSkip: "എനിക്ക് കേൾക്കാൻ കഴിഞ്ഞില്ല. ഈ ചോദ്യം ഒഴിവാക്കാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുവോ?",
    skipConfirmed: "ചോദ്യം ഒഴിവാക്കുന്നു.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  pa: {
    brandName: "ਮਾਈਗੁਰੂ",
    tagline: "ਆਵਾਜ਼-ਅਧਾਰਤ ਮਾਨਸਿਕ ਸਿਹਤ ਮੁਲਾਂਕਣ ਟੂਲ",
    howItWorks: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ",
    howItWorksDesc: "ਆਪਣੇ ਆਪ ਨੂੰ ਚੈੱਕ ਕਰਨ ਦਾ ਇੱਕ ਸਧਾਰਨ, ਨਿੱਜੀ ਤਰੀਕਾ",
    speakNaturally: "ਕੁਦਰਤੀ ਤੌਰ 'ਤੇ ਬੋਲੋ",
    speakNaturallyDesc: "ਆਪਣੀ ਆਵਾਜ਼ ਦੀ ਵਰਤੋਂ ਕਰਕੇ 10 ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਦਿਓ। ਦੋਸਤ ਨਾਲ ਗੱਲ ਕਰਨ ਵਾਂਗ ਕੁਦਰਤੀ ਤੌਰ 'ਤੇ ਬੋਲੋ।",
    aiAnalysis: "AI ਵਿਸ਼ਲੇਸ਼ਣ",
    aiAnalysisDesc: "ਸਾਡਾ AI ਤੁਹਾਡੀ ਭਾਵਨਾਤਮਕ ਸਥਿਤੀ ਨੂੰ ਸਮਝਣ ਲਈ ਤੁਹਾਡੀਆਂ ਪ੍ਰਤੀਕਿਰਿਆਵਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਦਾ ਹੈ।",
    personalReport: "ਨਿੱਜੀ ਰਿਪੋਰਟ",
    personalReportDesc: "ਆਪਣੀ ਭਲਾਈ ਲਈ ਸੂਝ ਅਤੇ ਸਿਫਾਰਸ਼ਾਂ ਨਾਲ ਇੱਕ ਨਿੱਜੀ ਰਿਪੋਰਟ ਪ੍ਰਾਪਤ ਕਰੋ।",
    beginAssessment: "ਮੁਲਾਂਕਣ ਸ਼ੁਰੂ ਕਰੋ",
    privateDisclaimer: "ਤੁਹਾਡੀਆਂ ਪ੍ਰਤੀਕਿਰਿਆਵਾਂ ਨਿੱਜੀ ਤੌਰ 'ਤੇ ਪ੍ਰੋਸੈਸ ਕੀਤੀਆਂ ਜਾਂਦੀਆਂ ਹਨ ਅਤੇ ਸਟੋਰ ਨਹੀਂ ਕੀਤੀਆਂ ਜਾਂਦੀਆਂ",
    disclaimer: "ਇਹ ਟੂਲ ਸਿਰਫ਼ ਸਵੈ-ਪੜਚੋਲ ਲਈ ਹੈ ਅਤੇ ਪੇਸ਼ੇਵਰ ਮਾਨਸਿਕ ਸਿਹਤ ਦੇਖਭਾਲ ਦਾ ਬਦਲ ਨਹੀਂ ਹੈ।",
    selectLanguage: "ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ",
    recording: "ਰਿਕਾਰਡਿੰਗ...",
    tapToStop: "ਰੋਕਣ ਲਈ ਟੈਪ ਕਰੋ",
    tapToStart: "ਬੋਲਣਾ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਟੈਪ ਕਰੋ",
    processing: "ਤੁਹਾਡੀ ਪ੍ਰਤੀਕਿਰਿਆ ਪ੍ਰੋਸੈਸ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...",
    typeResponse: "ਜਾਂ ਆਪਣਾ ਜਵਾਬ ਇੱਥੇ ਲਿਖੋ...",
    submit: "ਜਮ੍ਹਾਂ ਕਰੋ",
    or: "ਜਾਂ",
    reviewResponses: "ਆਪਣੀਆਂ ਪ੍ਰਤੀਕਿਰਿਆਵਾਂ ਦੀ ਸਮੀਖਿਆ ਕਰੋ",
    reviewDesc: "ਇੱਥੇ ਤੁਹਾਡੇ ਮੁਲਾਂਕਣ ਦਾ ਸਾਰ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਭਾਵਨਾ ਵਿਸ਼ਲੇਸ਼ਣ ਦੀ ਸਮੀਖਿਆ ਕਰੋ।",
    doYouAgree: "ਕੀ ਤੁਸੀਂ ਇਸ ਵਿਸ਼ਲੇਸ਼ਣ ਨਾਲ ਸਹਿਮਤ ਹੋ?",
    yes: "ਹਾਂ",
    no: "ਨਹੀਂ",
    maybe: "ਸ਼ਾਇਦ",
    generatingReport: "ਤੁਹਾਡੀ ਰਿਪੋਰਟ ਤਿਆਰ ਹੋ ਰਹੀ ਹੈ...",
    generatingReportDesc: "ਇਸ ਵਿੱਚ ਕੁਝ ਸਮਾਂ ਲੱਗ ਸਕਦਾ ਹੈ",
    downloadReport: "ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ",
    startOver: "ਦੁਬਾਰਾ ਸ਼ੁਰੂ ਕਰੋ",
    focusAreas: "ਧਿਆਨ ਦੇਣ ਵਾਲੇ ਖੇਤਰ",
    strengths: "ਤੁਹਾਡੀ ਤਾਕਤ",
    of: "ਦਾ",
    assessmentGreeting: "ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ। ਮੈਂ ਸੁਣਨ ਲਈ ਇੱਥੇ ਹਾਂ।",
    assessmentClosing: "ਸਾਂਝਾ ਕਰਨ ਲਈ ਧੰਨਵਾਦ। ਮੈਂ ਹੁਣ ਤੁਹਾਡੀ ਰਿਪੋਰਟ ਤਿਆਰ ਕਰ ਰਿਹਾ ਹਾਂ।",
    assessmentFallback: "ਮਾਫ਼ ਕਰਨਾ, ਮੈਂ ਸਮਝ ਨਹੀਂ ਸਕਿਆ। ਕੀ ਤੁਸੀਂ ਕਿਰਪਾ ਕਰਕੇ ਦੁਹਰਾ ਸਕਦੇ ਹੋ?",
    changeAnalysis: "ਵਿਸ਼ਲੇਸ਼ਣ ਬਦਲੋ",
    overridePositive: "ਸਕਾਰਾਤਮਕ",
    overrideNeutral: "ਨਿਰਪੱਖ",
    overrideNegative: "ਧਿਆਨ ਦੀ ਲੋੜ ਹੈ",
    exitAssessment: "ਮੁਲਾਂਕਣ ਤੋਂ ਬਾਹਰ ਜਾਓ",
    tapToBegin: "ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਟੈਪ ਕਰੋ",
    liveConversation: "ਲਾਈਵ ਗੱਲਬਾਤ",
    liveConversationIntro: "ਆਪਣੇ ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਕੁਦਰਤੀ ਤੌਰ 'ਤੇ ਬੋਲੋ।",
    statusIdle: "ਤਿਆਰ",
    statusListening: "ਸੁਣ ਰਿਹਾ ਹਾਂ",
    statusProcessing: "ਪ੍ਰੋਸੈਸਿੰਗ",
    statusSpeaking: "ਬੋਲ ਰਿਹਾ ਹਾਂ",
    askToSkip: "ਮੈਨੂੰ ਸੁਣਾਈ ਨਹੀਂ ਦਿੱਤਾ। ਕੀ ਤੁਸੀਂ ਇਸ ਸਵਾਲ ਨੂੰ ਛੱਡਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    skipConfirmed: "ਸਵਾਲ ਛੱਡਿਆ ਜਾ ਰਿਹਾ ਹੈ।",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },

  de: {
    brandName: "MyGuru",
    tagline: "Ein sprachbasiertes Tool zur Bewertung der psychischen Gesundheit",
    howItWorks: "Wie es funktioniert",
    howItWorksDesc: "Ein einfacher, privater Weg, um nach sich selbst zu sehen",
    speakNaturally: "Sprechen Sie natürlich",
    speakNaturallyDesc: "Beantworten Sie 10 Fragen mit Ihrer Stimme. Sprechen Sie ganz natürlich wie mit einem Freund.",
    aiAnalysis: "KI-Analyse",
    aiAnalysisDesc: "Unsere KI analysiert die Stimmung Ihrer Antworten, um Ihren emotionalen Zustand zu verstehen.",
    personalReport: "Persönlicher Bericht",
    personalReportDesc: "Erhalten Sie einen personalisierten Bericht mit Erkenntnissen und Empfehlungen für Ihr Wohlbefinden.",
    beginAssessment: "Bewertung starten",
    privateDisclaimer: "Ihre Antworten werden privat verarbeitet und nicht gespeichert",
    disclaimer: "Dieses Tool dient nur zur Selbstreflexion und ersetzt keine professionelle psychologische Betreuung.",
    selectLanguage: "Wählen Sie Ihre bevorzugte Sprache",
    recording: "Aufnahme...",
    tapToStop: "Tippen zum Stoppen",
    tapToStart: "Tippen zum Sprechen",
    processing: "Ihre Antwort wird verarbeitet...",
    typeResponse: "Oder geben Sie Ihre Antwort hier ein...",
    submit: "Absenden",
    or: "oder",
    reviewResponses: "Überprüfen Sie Ihre Antworten",
    reviewDesc: "Hier ist eine Zusammenfassung Ihrer Bewertung. Bitte überprüfen Sie die Stimmungsanalyse.",
    doYouAgree: "Stimmen Sie dieser Analyse zu?",
    yes: "Ja",
    no: "Nein",
    maybe: "Vielleicht",
    generatingReport: "Ihr Bericht wird generiert...",
    generatingReportDesc: "Dies kann einen Moment dauern",
    downloadReport: "Bericht herunterladen",
    startOver: "Neu starten",
    focusAreas: "Schwerpunkte",
    strengths: "Ihre Stärken",
    of: "von",
    assessmentGreeting: "Hallo. Ich bin hier, um zuzuhören.",
    assessmentClosing: "Danke fürs Teilen. Ich erstelle jetzt Ihren Bericht.",
    assessmentFallback: "Entschuldigung, das habe ich nicht verstanden. Könnten Sie das bitte wiederholen?",
    changeAnalysis: "Analyse ändern",
    overridePositive: "Positiv",
    overrideNeutral: "Neutral",
    overrideNegative: "Braucht Aufmerksamkeit",
    exitAssessment: "Bewertung beenden",
    tapToBegin: "Tippen, um Gespräch zu beginnen",
    liveConversation: "Live-Gespräch",
    liveConversationIntro: "Sprechen Sie ganz natürlich in Ihr Mikrofon.",
    statusIdle: "Bereit",
    statusListening: "Zuhören",
    statusProcessing: "Verarbeiten",
    statusSpeaking: "Sprechen",
    askToSkip: "Ich habe Sie nicht gehört. Möchten Sie diese Frage überspringen?",
    skipConfirmed: "Frage wird übersprungen.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  it: {
    brandName: "MyGuru",
    tagline: "Uno strumento di valutazione della salute mentale basato sulla voce",
    howItWorks: "Come funziona",
    howItWorksDesc: "Un modo semplice e privato per controllare come stai",
    speakNaturally: "Parla naturalmente",
    speakNaturallyDesc: "Rispondi a 10 domande usando la tua voce. Parla naturalmente come faresti con un amico.",
    aiAnalysis: "Analisi IA",
    aiAnalysisDesc: "La nostra IA analizza il sentimento delle tue risposte per capire il tuo stato emotivo.",
    personalReport: "Rapporto personale",
    personalReportDesc: "Ricevi un rapporto personalizzato con approfondimenti e raccomandazioni per il tuo benessere.",
    beginAssessment: "Inizia valutazione",
    privateDisclaimer: "Le tue risposte vengono elaborate privatamente e non memorizzate",
    disclaimer: "Questo strumento è solo per l'auto-riflessione e non sostituisce l'assistenza professionale per la salute mentale.",
    selectLanguage: "Seleziona la tua lingua preferita",
    recording: "Registrazione...",
    tapToStop: "Tocca per fermare",
    tapToStart: "Tocca per iniziare a parlare",
    processing: "Elaborazione della tua risposta...",
    typeResponse: "O digita la tua risposta qui...",
    submit: "Invia",
    or: "o",
    reviewResponses: "Rivedi le tue risposte",
    reviewDesc: "Ecco un riepilogo della tua valutazione. Per favore rivedi l'analisi del sentimento.",
    doYouAgree: "Sei d'accordo con questa analisi?",
    yes: "Sì",
    no: "No",
    maybe: "Forse",
    generatingReport: "Generazione del rapporto...",
    generatingReportDesc: "Questo potrebbe richiedere un momento",
    downloadReport: "Scarica rapporto",
    startOver: "Ricomincia",
    focusAreas: "Aree di interesse",
    strengths: "I tuoi punti di forza",
    of: "di",
    assessmentGreeting: "Ciao. Sono qui per ascoltare.",
    assessmentClosing: "Grazie per aver condiviso. Sto generando il tuo rapporto ora.",
    assessmentFallback: "Mi dispiace, non ho capito. Potresti ripetere per favore?",
    changeAnalysis: "Cambia analisi",
    overridePositive: "Positivo",
    overrideNeutral: "Neutro",
    overrideNegative: "Richiede attenzione",
    exitAssessment: "Esci dalla valutazione",
    tapToBegin: "Tocca per iniziare la conversazione",
    liveConversation: "Conversazione dal vivo",
    liveConversationIntro: "Parla naturalmente usando il tuo microfono.",
    statusIdle: "Pronto",
    statusListening: "Ascolto",
    statusProcessing: "Elaborazione",
    statusSpeaking: "Parlando",
    askToSkip: "Non ti ho sentito. Vuoi saltare questa domanda?",
    skipConfirmed: "Salto la domanda.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  pt: {
    brandName: "MyGuru",
    tagline: "Uma ferramenta de avaliação de saúde mental baseada em voz",
    howItWorks: "Como funciona",
    howItWorksDesc: "Uma maneira simples e privada de verificar como você está",
    speakNaturally: "Fale naturalmente",
    speakNaturallyDesc: "Responda a 10 perguntas usando sua voz. Fale naturalmente como faria com um amigo.",
    aiAnalysis: "Análise de IA",
    aiAnalysisDesc: "Nossa IA analisa o sentimento de suas respostas para entender seu estado emocional.",
    personalReport: "Relatório Pessoal",
    personalReportDesc: "Receba um relatório personalizado com insights e recomendações para o seu bem-estar.",
    beginAssessment: "Iniciar Avaliação",
    privateDisclaimer: "Suas respostas são processadas de forma privada e não armazenadas",
    disclaimer: "Esta ferramenta é apenas para auto-reflexão e não substitui o atendimento profissional de saúde mental.",
    selectLanguage: "Selecione seu idioma preferido",
    recording: "Gravando...",
    tapToStop: "Toque para parar",
    tapToStart: "Toque para começar a falar",
    processing: "Processando sua resposta...",
    typeResponse: "Ou digite sua resposta aqui...",
    submit: "Enviar",
    or: "ou",
    reviewResponses: "Revise suas respostas",
    reviewDesc: "Aqui está um resumo da sua avaliação. Por favor, revise a análise de sentimento.",
    doYouAgree: "Você concorda com esta análise?",
    yes: "Sim",
    no: "Não",
    maybe: "Talvez",
    generatingReport: "Gerando seu relatório...",
    generatingReportDesc: "Isso pode levar um momento",
    downloadReport: "Baixar Relatório",
    startOver: "Recomeçar",
    focusAreas: "Áreas de Foco",
    strengths: "Seus Pontos Fortes",
    of: "de",
    assessmentGreeting: "Olá. Estou aqui para ouvir.",
    assessmentClosing: "Obrigado por compartilhar. Estou gerando seu relatório agora.",
    assessmentFallback: "Desculpe, não entendi. Poderia repetir, por favor?",
    changeAnalysis: "Alterar Análise",
    overridePositive: "Positivo",
    overrideNeutral: "Neutro",
    overrideNegative: "Precisa de Atenção",
    exitAssessment: "Sair da Avaliação",
    tapToBegin: "Toque para Iniciar Conversa",
    liveConversation: "Conversa ao Vivo",
    liveConversationIntro: "Fale naturalmente usando seu microfone.",
    statusIdle: "Pronto",
    statusListening: "Ouvindo",
    statusProcessing: "Processando",
    statusSpeaking: "Falando",
    askToSkip: "Não ouvi. Quer pular esta pergunta?",
    skipConfirmed: "Pulando pergunta.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  ru: {
    brandName: "MyGuru",
    tagline: "Голосовой инструмент оценки психического здоровья",
    howItWorks: "Как это работает",
    howItWorksDesc: "Простой и конфиденциальный способ проверить свое состояние",
    speakNaturally: "Говорите естественно",
    speakNaturallyDesc: "Ответьте на 10 вопросов голосом. Говорите естественно, как с другом.",
    aiAnalysis: "Анализ ИИ",
    aiAnalysisDesc: "Наш ИИ анализирует тональность ваших ответов, чтобы понять ваше эмоциональное состояние.",
    personalReport: "Личный отчет",
    personalReportDesc: "Получите персонализированный отчет с идеями и рекомендациями для вашего благополучия.",
    beginAssessment: "Начать оценку",
    privateDisclaimer: "Ваши ответы обрабатываются конфиденциально и не сохраняются",
    disclaimer: "Этот инструмент предназначен только для самоанализа и не заменяет профессиональную психиатрическую помощь.",
    selectLanguage: "Выберите предпочитаемый язык",
    recording: "Запись...",
    tapToStop: "Нажмите, чтобы остановить",
    tapToStart: "Нажмите, чтобы начать говорить",
    processing: "Обработка вашего ответа...",
    typeResponse: "Или введите ваш ответ здесь...",
    submit: "Отправить",
    or: "или",
    reviewResponses: "Проверьте свои ответы",
    reviewDesc: "Вот краткое изложение вашей оценки. Пожалуйста, проверьте анализ тональности.",
    doYouAgree: "Вы согласны с этим анализом?",
    yes: "Да",
    no: "Нет",
    maybe: "Возможно",
    generatingReport: "Создание отчета...",
    generatingReportDesc: "Это может занять некоторое время",
    downloadReport: "Скачать отчет",
    startOver: "Начать заново",
    focusAreas: "Области внимания",
    strengths: "Ваши сильные стороны",
    of: "из",
    assessmentGreeting: "Здравствуйте. Я здесь, чтобы выслушать.",
    assessmentClosing: "Спасибо, что поделились. Я создаю ваш отчет.",
    assessmentFallback: "Извините, я не расслышал. Не могли бы вы повторить?",
    changeAnalysis: "Изменить анализ",
    overridePositive: "Позитивный",
    overrideNeutral: "Нейтральный",
    overrideNegative: "Требует внимания",
    exitAssessment: "Выйти из оценки",
    tapToBegin: "Нажмите, чтобы начать разговор",
    liveConversation: "Живой разговор",
    liveConversationIntro: "Говорите естественно, используя микрофон.",
    statusIdle: "Готов",
    statusListening: "Слушаю",
    statusProcessing: "Обработка",
    statusSpeaking: "Говорю",
    askToSkip: "Я не расслышал. Вы хотите пропустить этот вопрос?",
    skipConfirmed: "Пропуск вопроса.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  th: {
    brandName: "MyGuru",
    tagline: "เครื่องมือประเมินสุขภาพจิตด้วยเสียง",
    howItWorks: "วิธีการทำงาน",
    howItWorksDesc: "วิธีง่ายๆ และเป็นส่วนตัวในการตรวจสอบตัวเอง",
    speakNaturally: "พูดตามธรรมชาติ",
    speakNaturallyDesc: "ตอบคำถาม 10 ข้อโดยใช้เสียงของคุณ พูดตามธรรมชาติเหมือนคุยกับเพื่อน",
    aiAnalysis: "การวิเคราะห์ AI",
    aiAnalysisDesc: "AI ของเราวิเคราะห์ความรู้สึกของคำตอบของคุณเพื่อเข้าใจสภาวะทางอารมณ์ของคุณ",
    personalReport: "รายงานส่วนตัว",
    personalReportDesc: "รับรายงานส่วนตัวพร้อมข้อมูลเชิงลึกและคำแนะนำเพื่อความเป็นอยู่ที่ดีของคุณ",
    beginAssessment: "เริ่มการประเมิน",
    privateDisclaimer: "คำตอบของคุณได้รับการประมวลผลแบบส่วนตัวและไม่ได้จัดเก็บไว้",
    disclaimer: "เครื่องมือนี้มีไว้สำหรับการสะท้อนตนเองเท่านั้นและไม่ได้ใช้แทนการดูแลสุขภาพจิตโดยผู้เชี่ยวชาญ",
    selectLanguage: "เลือกภาษาที่คุณต้องการ",
    recording: "กำลังบันทึก...",
    tapToStop: "แตะเพื่อหยุด",
    tapToStart: "แตะเพื่อเริ่มพูด",
    processing: "กำลังประมวลผลคำตอบของคุณ...",
    typeResponse: "หรือพิมพ์คำตอบของคุณที่นี่...",
    submit: "ส่ง",
    or: "หรือ",
    reviewResponses: "ตรวจสอบคำตอบของคุณ",
    reviewDesc: "นี่คือสรุปผลการประเมินของคุณ โปรดตรวจสอบการวิเคราะห์ความรู้สึก",
    doYouAgree: "คุณเห็นด้วยกับการวิเคราะห์นี้หรือไม่?",
    yes: "ใช่",
    no: "ไม่",
    maybe: "อาจจะ",
    generatingReport: "กำลังสร้างรายงานของคุณ...",
    generatingReportDesc: "อาจใช้เวลาสักครู่",
    downloadReport: "ดาวน์โหลดรายงาน",
    startOver: "เริ่มต้นใหม่",
    focusAreas: "จุดที่ควรเน้น",
    strengths: "จุดแข็งของคุณ",
    of: "จาก",
    assessmentGreeting: "สวัสดี ฉันอยู่ที่นี่เพื่อรับฟัง",
    assessmentClosing: "ขอบคุณที่แบ่งปัน ฉันกำลังสร้างรายงานของคุณ",
    assessmentFallback: "ขอโทษ ฉันฟังไม่ทัน ช่วยพูดซ้ำได้ไหม?",
    changeAnalysis: "เปลี่ยนการวิเคราะห์",
    overridePositive: "เชิงบวก",
    overrideNeutral: "เป็นกลาง",
    overrideNegative: "ต้องการความสนใจ",
    exitAssessment: "ออกจากการประเมิน",
    tapToBegin: "แตะเพื่อเริ่มการสนทนา",
    liveConversation: "การสนทนาสด",
    liveConversationIntro: "พูดตามธรรมชาติโดยใช้ไมโครโฟนของคุณ",
    statusIdle: "พร้อม",
    statusListening: "กำลังฟัง",
    statusProcessing: "กำลังประมวลผล",
    statusSpeaking: "กำลังพูด",
    askToSkip: "ฉันไม่ได้ยิน คุณต้องการข้ามคำถามนี้หรือไม่?",
    skipConfirmed: "กำลังข้ามคำถาม",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  vi: {
    brandName: "MyGuru",
    tagline: "Công cụ đánh giá sức khỏe tâm thần dựa trên giọng nói",
    howItWorks: "Cách Hoạt Động",
    howItWorksDesc: "Một cách đơn giản, riêng tư để kiểm tra bản thân",
    speakNaturally: "Nói Tự Nhiên",
    speakNaturallyDesc: "Trả lời 10 câu hỏi bằng giọng nói của bạn. Nói chuyện tự nhiên như với một người bạn.",
    aiAnalysis: "Phân Tích AI",
    aiAnalysisDesc: "AI của chúng tôi phân tích cảm xúc trong câu trả lời của bạn để hiểu trạng thái cảm xúc của bạn.",
    personalReport: "Báo Cáo Cá Nhân",
    personalReportDesc: "Nhận báo cáo cá nhân với những hiểu biết và đề xuất cho sức khỏe của bạn.",
    beginAssessment: "Bắt Đầu Đánh Giá",
    privateDisclaimer: "Câu trả lời của bạn được xử lý riêng tư và không được lưu trữ",
    disclaimer: "Công cụ này chỉ dành cho mục đích tự phản ánh và không thay thế cho chăm sóc sức khỏe tâm thần chuyên nghiệp.",
    selectLanguage: "Chọn ngôn ngữ ưu tiên của bạn",
    recording: "Đang ghi âm...",
    tapToStop: "Nhấn để dừng",
    tapToStart: "Nhấn để bắt đầu nói",
    processing: "Đang xử lý câu trả lời của bạn...",
    typeResponse: "Hoặc nhập câu trả lời của bạn tại đây...",
    submit: "Gửi",
    or: "hoặc",
    reviewResponses: "Xem Lại Câu Trả Lời Của Bạn",
    reviewDesc: "Đây là tóm tắt đánh giá của bạn. Vui lòng xem lại phân tích cảm xúc.",
    doYouAgree: "Bạn có đồng ý với phân tích này không?",
    yes: "Có",
    no: "Không",
    maybe: "Có lẽ",
    generatingReport: "Đang tạo báo cáo của bạn...",
    generatingReportDesc: "Việc này có thể mất một chút thời gian",
    downloadReport: "Tải Xuống Báo Cáo",
    startOver: "Bắt Đầu Lại",
    focusAreas: "Lĩnh Vực Trọng Tâm",
    strengths: "Điểm Mạnh Của Bạn",
    of: "của",
    assessmentGreeting: "Xin chào. Tôi ở đây để lắng nghe.",
    assessmentClosing: "Cảm ơn bạn đã chia sẻ. Tôi đang tạo báo cáo của bạn ngay bây giờ.",
    assessmentFallback: "Xin lỗi, tôi không nghe rõ. Bạn có thể lặp lại không?",
    changeAnalysis: "Thay đổi Phân tích",
    overridePositive: "Tích cực",
    overrideNeutral: "Trung lập",
    overrideNegative: "Cần chú ý",
    exitAssessment: "Thoát đánh giá",
    tapToBegin: "Nhấn để bắt đầu cuộc trò chuyện",
    liveConversation: "Cuộc trò chuyện trực tiếp",
    liveConversationIntro: "Nói chuyện tự nhiên bằng micrô của bạn.",
    statusIdle: "Sẵn sàng",
    statusListening: "Đang nghe",
    statusProcessing: "Đang xử lý",
    statusSpeaking: "Đang nói",
    askToSkip: "Tôi không nghe rõ. Bạn có muốn bỏ qua câu hỏi này không?",
    skipConfirmed: "Bỏ qua câu hỏi.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  id: {
    brandName: "MyGuru",
    tagline: "Alat penilaian kesehatan mental berbasis suara",
    howItWorks: "Cara Kerja",
    howItWorksDesc: "Cara sederhana dan pribadi untuk memeriksa diri sendiri",
    speakNaturally: "Bicaralah Secara Alami",
    speakNaturallyDesc: "Jawab 10 pertanyaan menggunakan suara Anda. Bicaralah secara alami seperti kepada teman.",
    aiAnalysis: "Analisis AI",
    aiAnalysisDesc: "AI kami menganalisis sentimen tanggapan Anda untuk memahami keadaan emosional Anda.",
    personalReport: "Laporan Pribadi",
    personalReportDesc: "Terima laporan yang dipersonalisasi dengan wawasan dan rekomendasi untuk kesejahteraan Anda.",
    beginAssessment: "Mulai Penilaian",
    privateDisclaimer: "Tanggapan Anda diproses secara pribadi dan tidak disimpan",
    disclaimer: "Alat ini hanya untuk tujuan refleksi diri dan bukan pengganti perawatan kesehatan mental profesional.",
    selectLanguage: "Pilih bahasa pilihan Anda",
    recording: "Merekam...",
    tapToStop: "Ketuk untuk berhenti",
    tapToStart: "Ketuk untuk mulai berbicara",
    processing: "Memproses tanggapan Anda...",
    typeResponse: "Atau ketik jawaban Anda di sini...",
    submit: "Kirim",
    or: "atau",
    reviewResponses: "Tinjau Tanggapan Anda",
    reviewDesc: "Berikut adalah ringkasan penilaian Anda. Harap tinjau analisis sentimen.",
    doYouAgree: "Apakah Anda setuju dengan analisis ini?",
    yes: "Ya",
    no: "Tidak",
    maybe: "Mungkin",
    generatingReport: "Menghasilkan laporan Anda...",
    generatingReportDesc: "Ini mungkin memakan waktu sebentar",
    downloadReport: "Unduh Laporan",
    startOver: "Mulai Lagi",
    focusAreas: "Area Fokus",
    strengths: "Kekuatan Anda",
    of: "dari",
    assessmentGreeting: "Halo. Saya di sini untuk mendengarkan.",
    assessmentClosing: "Terima kasih telah berbagi. Saya sedang membuat laporan Anda sekarang.",
    assessmentFallback: "Maaf, saya tidak menangkap itu. Bisakah Anda ulangi?",
    changeAnalysis: "Ubah Analisis",
    overridePositive: "Positif",
    overrideNeutral: "Netral",
    overrideNegative: "Butuh Perhatian",
    exitAssessment: "Keluar dari Penilaian",
    tapToBegin: "Ketuk untuk Memulai Percakapan",
    liveConversation: "Percakapan Langsung",
    liveConversationIntro: "Bicaralah secara alami menggunakan mikrofon Anda.",
    statusIdle: "Siap",
    statusListening: "Mendengarkan",
    statusProcessing: "Memproses",
    statusSpeaking: "Berbicara",
    askToSkip: "Saya tidak mendengar Anda. Apakah Anda ingin melewatkan pertanyaan ini?",
    skipConfirmed: "Melewatkan pertanyaan.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  ar: {
    brandName: "MyGuru",
    tagline: "أداة تقييم الصحة العقلية القائمة على الصوت",
    howItWorks: "كيف تعمل",
    howItWorksDesc: "طريقة بسيطة وخاصة للتحقق من نفسك",
    speakNaturally: "تحدث بشكل طبيعي",
    speakNaturallyDesc: "أجب عن 10 أسئلة باستخدام صوتك. تحدث بشكل طبيعي كما تفعل مع صديق.",
    aiAnalysis: "تحليل الذكاء الاصطناعي",
    aiAnalysisDesc: "يقوم الذكاء الاصطناعي لدينا بتحليل مشاعر ردودك لفهم حالتك العاطفية.",
    personalReport: "تقرير شخصي",
    personalReportDesc: "احصل على تقرير مخصص يحتوي على رؤى وتوصيات لرفاهيتك.",
    beginAssessment: "بدء التقييم",
    privateDisclaimer: "تتم معالجة ردودك بشكل خاص ولا يتم تخزينها",
    disclaimer: "هذه الأداة مخصصة للتأمل الذاتي فقط وليست بديلاً عن الرعاية المهنية للصحة العقلية.",
    selectLanguage: "اختر لغتك المفضلة",
    recording: "جاري التسجيل...",
    tapToStop: "اضغط للتوقف",
    tapToStart: "اضغط لبدء التحدث",
    processing: "جاري معالجة ردك...",
    typeResponse: "أو اكتب إجابتك هنا...",
    submit: "إرسال",
    or: "أو",
    reviewResponses: "راجع إجاباتك",
    reviewDesc: "إليك ملخص لتقييمك. يرجى مراجعة تحليل المشاعر.",
    doYouAgree: "هل توافق على هذا التحليل؟",
    yes: "نعم",
    no: "لا",
    maybe: "ربما",
    generatingReport: "جاري إنشاء تقريرك...",
    generatingReportDesc: "قد يستغرق هذا لحظة",
    downloadReport: "تنزيل التقرير",
    startOver: "البدء من جديد",
    focusAreas: "مجالات التركيز",
    strengths: "نقاط قوتك",
    of: "من",
    assessmentGreeting: "مرحباً. أنا هنا للاستماع.",
    assessmentClosing: "شكراً للمشاركة. أقوم بإنشاء تقريرك الآن.",
    assessmentFallback: "أنا آسف، لم ألتقط ذلك. هل يمكنك التكرار من فضلك؟",
    changeAnalysis: "تغيير التحليل",
    overridePositive: "إيجابي",
    overrideNeutral: "محايد",
    overrideNegative: "يحتاج إلى اهتمام",
    exitAssessment: "خروج من التقييم",
    tapToBegin: "انقر لبدء المحادثة",
    liveConversation: "محادثة حية",
    liveConversationIntro: "تحدث بشكل طبيعي باستخدام الميكروفون.",
    statusIdle: "جاهز",
    statusListening: "استماع",
    statusProcessing: "معالجة",
    statusSpeaking: "تحدث",
    askToSkip: "لم أسمعك. هل تريد تخطي هذا السؤال؟",
    skipConfirmed: "تخطي السؤال.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
  tr: {
    brandName: "MyGuru",
    tagline: "Ses tabanlı zihinsel sağlık değerlendirme aracı",
    howItWorks: "Nasıl Çalışır",
    howItWorksDesc: "Kendinizi kontrol etmenin basit, özel bir yolu",
    speakNaturally: "Doğal Konuşun",
    speakNaturallyDesc: "Sesinizi kullanarak 10 soruyu yanıtlayın. Bir arkadaşınızla konuşuyormuş gibi doğal konuşun.",
    aiAnalysis: "Yapay Zeka Analizi",
    aiAnalysisDesc: "Yapay zekamız, duygusal durumunuzu anlamak için yanıtlarınızın duygu analizini yapar.",
    personalReport: "Kişisel Rapor",
    personalReportDesc: "Refahınız için içgörüler ve öneriler içeren kişiselleştirilmiş bir rapor alın.",
    beginAssessment: "Değerlendirmeyi Başlat",
    privateDisclaimer: "Yanıtlarınız özel olarak işlenir ve saklanmaz",
    disclaimer: "Bu araç yalnızca kendini yansıtma amaçlıdır ve profesyonel ruh sağlığı bakımının yerini tutmaz.",
    selectLanguage: "Tercih ettiğiniz dili seçin",
    recording: "Kaydediliyor...",
    tapToStop: "Durdurmak için dokunun",
    tapToStart: "Konuşmaya başlamak için dokunun",
    processing: "Yanıtınız işleniyor...",
    typeResponse: "Veya yanıtınızı buraya yazın...",
    submit: "Gönder",
    or: "veya",
    reviewResponses: "Yanıtlarınızı Gözden Geçirin",
    reviewDesc: "İşte değerlendirmenizin bir özeti. Lütfen duygu analizini gözden geçirin.",
    doYouAgree: "Bu analize katılıyor musunuz?",
    yes: "Evet",
    no: "Hayır",
    maybe: "Belki",
    generatingReport: "Raporunuz oluşturuluyor...",
    generatingReportDesc: "Bu bir dakika sürebilir",
    downloadReport: "Raporu İndir",
    startOver: "Baştan Başla",
    focusAreas: "Odak Alanları",
    strengths: "Güçlü Yönleriniz",
    of: "/",
    assessmentGreeting: "Merhaba. Dinlemek için buradayım.",
    assessmentClosing: "Paylaştığınız için teşekkürler. Raporunuzu şimdi oluşturuyorum.",
    assessmentFallback: "Üzgünüm, bunu yakalayamadım. Tekrar eder misiniz?",
    changeAnalysis: "Analizi Değiştir",
    overridePositive: "Olumlu",
    overrideNeutral: "Nötr",
    overrideNegative: "İlgi Gerektiriyor",
    exitAssessment: "Değerlendirmeden Çık",
    tapToBegin: "Görüşmeyi Başlatmak için Dokun",
    liveConversation: "Canlı Görüşme",
    liveConversationIntro: "Mikrofonunuzu kullanarak doğal bir şekilde konuşun.",
    statusIdle: "Hazır",
    statusListening: "Dinliyor",
    statusProcessing: "İşleniyor",
    statusSpeaking: "Konuşuyor",
    askToSkip: "Sizi duyamadım. Bu soruyu geçmek ister misiniz?",
    skipConfirmed: "Soru geçiliyor.",
    priorityHigh: "High Priority",
    priorityMedium: "Medium Priority",
    priorityLow: "Low Priority",
    statusPositive: "Positive",
    statusBalanced: "Balanced",
    statusNeedsSupport: "Needs Support",
  },
}

// Get translation or fallback to English
export function getTranslation(langCode: string) {
  return UI_TRANSLATIONS[langCode] || UI_TRANSLATIONS.en
}

export function getQuestions(langCode: string) {
  return QUESTIONS[langCode] || QUESTIONS.en
}

export function getLanguageByCode(code: string): Language | undefined {
  return SUPPORTED_LANGUAGES.find(lang => lang.code === code)
}
